<option value="AG">Aguascalientes</option>
<option value="AL">Alabama</option>
<option value="AK">Alaska</option>
<option value="AB">Alberta</option>
<option value="AS">American Samoa</option>
<option value="AZ">Arizona</option>
<option value="AR">Arkansas</option>
<option value="AE">Armed Forces Africa (AE)</option>
<option value="AA">Armed Forces Americas (AA)</option>
<option value="AE">Armed Forces Canada (AE)</option>
<option value="AE">Armed Forces Europe (AE)</option>
<option value="AE">Armed Forces Middle East (AE)</option>
<option value="AP">Armed Forces Pacific (AP)</option>
<option value="BN">Baja California Norte</option>
<option value="BS">Baja California Sur</option>
<option value="BC">British Columbia</option>
<option value="CA">California</option>
<option value="CP">Campeche</option>
<option value="CS">Chiapas</option>
<option value="CI">Chihuahua</option>
<option value="CH">Coahuila</option>
<option value="CL">Colima</option>
<option value="CO">Colorado</option>
<option value="CT">Connecticut</option>
<option value="DE">Delaware</option>
<option value="DC">District Of Columbia</option>
<option value="DF">Districto Federal</option>
<option value="DG">Durango</option>
<option value="FL">Florida</option>
<option value="GA">Georgia</option>
<option value="GU">Guam</option>
<option value="GJ">Guanajuato</option>
<option value="GE">Guerrero</option>
<option value="HI">Hawaii</option>
<option value="HD">Hidalgo</option>
<option value="ID">Idaho</option>
<option value="IL">Illinois</option>
<option value="IN">Indiana</option>
<option value="IA">Iowa</option>
<option value="JA">Jalisco</option>
<option value="KS">Kansas</option>
<option value="KY">Kentucky</option>
<option value="LA">Louisiana</option>
<option value="ME">Maine</option>
<option value="MB">Manitoba</option>
<option value="MH">Marshall Islands</option>
<option value="MD">Maryland</option>
<option value="MA">Massachusetts</option>
<option value="MI">Michigan</option>
<option value="MN">Minnesota</option>
<option value="MS">Mississippi</option>
<option value="MO">Missouri</option>
<option value="MT">Montana</option>
<option value="NE">Nebraska</option>
<option value="NV">Nevada</option>
<option value="NB">New Brunswick</option>
<option value="NH">New Hampshire</option>
<option value="NJ">New Jersey</option>
<option value="NM">New Mexico</option>
<option value="NY">New York</option>
<option value="NF">Newfoundland</option>
<option value="NC">North Carolina</option>
<option value="ND">North Dakota</option>
<option value="MP">Northern Mariana Is</option>
<option value="NT">Northwest Territories</option>
<option value="NS">Nova Scotia</option>
<option value="OH">Ohio</option>
<option value="OK">Oklahoma</option>
<option value="ON">Ontario</option>
<option value="OR">Oregon</option>
<option value="PW">Palau</option>
<option value="PA">Pennsylvania</option>
<option value="PE">Prince Edward Island</option>
<option value="PQ">Province du Quebec</option>
<option value="PU">Puebla</option>
<option value="PR">Puerto Rico</option>
<option value="QE">Quer&#233;taro</option>
<option value="QI">Quintana Roo</option>
<option value="RI">Rhode Island</option>
<option value="SL">San Luis Potos&#237;</option>
<option value="SK">Saskatchewan</option>
<option value="SI">Sinaloa</option>
<option value="SO">Sonora</option>
<option value="SC">South Carolina</option>
<option value="SD">South Dakota</option>
<option value="TB">Tabasco</option>
<option value="TA">Tamaulipas</option>
<option value="TN">Tennessee</option>
<option value="TX">Texas</option>
<option value="TL">Tlaxcala</option>
<option value="UT">Utah</option>
<option value="VC">Veracruz</option>
<option value="VT">Vermont</option>
<option value="VI">Virgin Islands</option>
<option value="VA">Virginia</option>
<option value="WA">Washington</option>
<option value="WV">West Virginia</option>
<option value="WI">Wisconsin</option>
<option value="WY">Wyoming</option>
<option value="YU">Yucat&#225;n</option>
<option value="YT">Yukon Territory</option>
<option value="ZA">Zacatecas</option>
