/** 
 *  Authors: @author@
 *  Release: @release@
 *	
 *  '$Author: harris $'
 *  '$Date: 2001-10-12 18:36:22 $'
 * 	'$Revision: 1.2 $'
 */
package vegclient.framework;

import javax.swing.*;
import vegclient.framework.*;

public class ConfigurationInterface extends javax.swing.JFrame {
    
    //utility classes
    ClientFramework framework = new ClientFramework();
    ConfigurationFile config = new ConfigurationFile();
    
    //database plugins
    String[] databasePlugins = 
    {   "vegclient.databasemanager.PostgresLinuxPlugin", 
        "vegclient.databasemanager.PostgresNTPlugin", 
        "vegclient.databasemanager.HypersonicSQLPlugin"
    };

    
    /** Creates new form ConfigurationInterface */
    public ConfigurationInterface() 
    {
        initComponents();
        setTitle("ConfigurationInterface - build: @release@ ");
        setSize(400, 500);
        
        //get all the settings from the configuration file class
        workingDirectoryTextField.setText( config.workingDirectory);
        servletLocationTextField.setText( config.servletLocation );
        servletUserNameTextField.setText( config.servletUserName );
        servletPassWordTextField.setText( config.servletPassWord );
            
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        mainPane = new javax.swing.JPanel();
        generalSettingsPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workingDirectoryTextField = new javax.swing.JTextField();
        workingDirectoryChooserButton = new javax.swing.JButton();
        networkConnectionPane = new javax.swing.JPanel();
        servletLocationPane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        servletLocationTextField = new javax.swing.JTextField();
        userNamePane = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        servletUserNameTextField = new javax.swing.JTextField();
        servletPasswordName = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        servletPassWordTextField = new javax.swing.JTextField();
        localDatabasePane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        databasePluginComboPane = new JComboBox( databasePlugins );
        updatePane = new javax.swing.JPanel();
        updateConfigurationButton = new javax.swing.JButton();
        
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        
        mainPane.setLayout(new javax.swing.BoxLayout(mainPane, javax.swing.BoxLayout.Y_AXIS));
        
        generalSettingsPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        generalSettingsPane.setPreferredSize(new java.awt.Dimension(387, 44));
        generalSettingsPane.setMinimumSize(new java.awt.Dimension(266, 44));
        generalSettingsPane.setMaximumSize(new java.awt.Dimension(32767, 44));
        jLabel2.setText("Working Directory: ");
        generalSettingsPane.add(jLabel2);
        
        workingDirectoryTextField.setBackground(java.awt.Color.pink);
        workingDirectoryTextField.setPreferredSize(new java.awt.Dimension(140, 17));
        workingDirectoryTextField.setMaximumSize(new java.awt.Dimension(140, 2147483647));
        workingDirectoryTextField.setMinimumSize(new java.awt.Dimension(140, 17));
        jScrollPane1.setViewportView(workingDirectoryTextField);
        
        generalSettingsPane.add(jScrollPane1);
        
        workingDirectoryChooserButton.setText("Choose");
        workingDirectoryChooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workingDirectoryChooserButtonActionPerformed(evt);
            }
        });
        
        generalSettingsPane.add(workingDirectoryChooserButton);
        
        mainPane.add(generalSettingsPane);
        
        networkConnectionPane.setLayout(new javax.swing.BoxLayout(networkConnectionPane, javax.swing.BoxLayout.Y_AXIS));
        
        networkConnectionPane.setBorder(new javax.swing.border.EtchedBorder());
        networkConnectionPane.setPreferredSize(new java.awt.Dimension(278, 120));
        networkConnectionPane.setMinimumSize(new java.awt.Dimension(278, 120));
        networkConnectionPane.setMaximumSize(new java.awt.Dimension(32771, 120));
        servletLocationPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jLabel3.setText("Servlet Location:");
        servletLocationPane.add(jLabel3);
        
        servletLocationTextField.setBackground(java.awt.Color.pink);
        servletLocationTextField.setPreferredSize(new java.awt.Dimension(140, 17));
        servletLocationTextField.setMaximumSize(new java.awt.Dimension(140, 2147483647));
        servletLocationTextField.setMinimumSize(new java.awt.Dimension(140, 17));
        servletLocationPane.add(servletLocationTextField);
        
        networkConnectionPane.add(servletLocationPane);
        
        userNamePane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jLabel4.setText("User Name:");
        userNamePane.add(jLabel4);
        
        servletUserNameTextField.setBackground(java.awt.Color.pink);
        servletUserNameTextField.setPreferredSize(new java.awt.Dimension(140, 17));
        servletUserNameTextField.setMaximumSize(new java.awt.Dimension(140, 2147483647));
        servletUserNameTextField.setMinimumSize(new java.awt.Dimension(140, 17));
        userNamePane.add(servletUserNameTextField);
        
        networkConnectionPane.add(userNamePane);
        
        servletPasswordName.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jLabel5.setText("Password: ");
        servletPasswordName.add(jLabel5);
        
        servletPassWordTextField.setBackground(java.awt.Color.pink);
        servletPassWordTextField.setPreferredSize(new java.awt.Dimension(140, 17));
        servletPassWordTextField.setMaximumSize(new java.awt.Dimension(140, 2147483647));
        servletPassWordTextField.setMinimumSize(new java.awt.Dimension(140, 17));
        servletPasswordName.add(servletPassWordTextField);
        
        networkConnectionPane.add(servletPasswordName);
        
        mainPane.add(networkConnectionPane);
        
        localDatabasePane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        localDatabasePane.setPreferredSize(new java.awt.Dimension(269, 45));
        localDatabasePane.setMinimumSize(new java.awt.Dimension(265, 45));
        localDatabasePane.setMaximumSize(new java.awt.Dimension(32767, 45));
        jLabel1.setText("Database Plugin: ");
        localDatabasePane.add(jLabel1);
        
        databasePluginComboPane.setBackground(java.awt.Color.pink);
        localDatabasePane.add(databasePluginComboPane);
        
        mainPane.add(localDatabasePane);
        
        updatePane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 34));
        
        updateConfigurationButton.setText("Update Configuration");
        updateConfigurationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateConfigurationButtonActionPerformed(evt);
            }
        });
        
        updatePane.add(updateConfigurationButton);
        
        mainPane.add(updatePane);
        
        getContentPane().add(mainPane);
        
        pack();
    }//GEN-END:initComponents

    private void workingDirectoryChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workingDirectoryChooserButtonActionPerformed
        // Add your handling code here:
        System.out.println("Choosing a new working Directory");
        String newWorkingDir = framework.directoryChooser();
        if ( newWorkingDir == null )
        {
            framework.debug(0, "not a valid working directory");
        }
        else
        {
          workingDirectoryTextField.setText(newWorkingDir);   
        }
    }//GEN-LAST:event_workingDirectoryChooserButtonActionPerformed

    private void updateConfigurationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateConfigurationButtonActionPerformed
        // Add your handling code here:
        System.out.println("Updating the configuration settings");
        String plugin = (String)databasePluginComboPane.getSelectedItem();
        
        //this replaces the name of the plugin
        config.replacePlugin(plugin);
        
        //replaces the working directory
        config.replaceWorkingDirectory( workingDirectoryTextField.getText() );
        
        
        
    }//GEN-LAST:event_updateConfigurationButtonActionPerformed
   /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        //System.exit(0);
        this.dispose();
        
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        new ConfigurationInterface().show();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPane;
    private javax.swing.JPanel generalSettingsPane;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField workingDirectoryTextField;
    private javax.swing.JButton workingDirectoryChooserButton;
    private javax.swing.JPanel networkConnectionPane;
    private javax.swing.JPanel servletLocationPane;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField servletLocationTextField;
    private javax.swing.JPanel userNamePane;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField servletUserNameTextField;
    private javax.swing.JPanel servletPasswordName;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField servletPassWordTextField;
    private javax.swing.JPanel localDatabasePane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox databasePluginComboPane;
    private javax.swing.JPanel updatePane;
    private javax.swing.JButton updateConfigurationButton;
    // End of variables declaration//GEN-END:variables

}
