package vegclient.framework;

/**
 * DatabaseManagerInterface.java
 *
 * Created on September 28, 2001, 3:12 PM
 *  Authors: @author@
 *  Release: @release@
 *	
 *  '$Author: harris $'
 *  '$Date: 2001-10-10 18:12:41 $'
 * 	'$Revision: 1.3 $'
 */

import vegclient.framework.*;
import vegclient.databasemanager.*;

/**
 *
 * @author  harris
 */
public class DatabaseManagerInterface extends javax.swing.JFrame {

    //classes used in this class
    DatabaseManager manager = new DatabaseManager();
    ClientFramework framework = new ClientFramework();
    
    /** Creates new form DatabaseManagerInterface */
    public DatabaseManagerInterface () {
        initComponents();
        setSize(600, 300);
        setTitle("DatabaseManagerInterface: @release@ ");
        
        //update the text areas from the content in the config.xml file 
        //and the DatabaseManager class
        
        osTypeTextField.setText( manager.OSType);
        rdbmsTypeTextField.setText( manager.RDBMSType);
        initDirectoryTextField.setText( manager.dataDirectory );
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        DatabaseInitializationPane = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        osTypeTextField = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rdbmsTypeTextField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        chooseInitDirectoryButton = new javax.swing.JButton();
        initDirectoryTextField = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        initializeDatabaseButton = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        createDatabaseButton = new javax.swing.JButton();
        DatabaseStartupPane = new javax.swing.JPanel();
        startupPane = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        databaseStartupButton = new javax.swing.JButton();
        shutdownPane = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        databaseShutdownButton = new javax.swing.JButton();
        DatabaseTablesPane = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        createBaseTablesButton = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        createSummaryTables = new javax.swing.JButton();
        DatabaseUsersPane = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        createUserButton = new javax.swing.JButton();
        
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        
        DatabaseInitializationPane.setLayout(new javax.swing.BoxLayout(DatabaseInitializationPane, javax.swing.BoxLayout.Y_AXIS));
        
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jPanel6.setPreferredSize(new java.awt.Dimension(310, 11));
        jPanel6.setMinimumSize(new java.awt.Dimension(194, 17));
        jLabel1.setText("Operating System Type: ");
        jPanel6.add(jLabel1);
        
        osTypeTextField.setBackground(java.awt.Color.pink);
        osTypeTextField.setPreferredSize(new java.awt.Dimension(120, 17));
        jPanel6.add(osTypeTextField);
        
        DatabaseInitializationPane.add(jPanel6);
        
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jPanel7.setPreferredSize(new java.awt.Dimension(225, 11));
        jPanel7.setMinimumSize(new java.awt.Dimension(225, 17));
        jLabel2.setText("RDBMS Type:");
        jPanel7.add(jLabel2);
        
        rdbmsTypeTextField.setBackground(java.awt.Color.pink);
        rdbmsTypeTextField.setPreferredSize(new java.awt.Dimension(120, 17));
        rdbmsTypeTextField.setMinimumSize(new java.awt.Dimension(120, 17));
        jPanel7.add(rdbmsTypeTextField);
        
        DatabaseInitializationPane.add(jPanel7);
        
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        chooseInitDirectoryButton.setText("Initialization Directory");
        chooseInitDirectoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseInitDirectoryButtonActionPerformed(evt);
            }
        });
        
        jPanel5.add(chooseInitDirectoryButton);
        
        initDirectoryTextField.setBackground(java.awt.Color.pink);
        initDirectoryTextField.setPreferredSize(new java.awt.Dimension(200, 17));
        initDirectoryTextField.setMinimumSize(new java.awt.Dimension(200, 17));
        jPanel5.add(initDirectoryTextField);
        
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        initializeDatabaseButton.setText("Initialize Database");
        initializeDatabaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initializeDatabaseButtonActionPerformed(evt);
            }
        });
        
        jPanel8.add(initializeDatabaseButton);
        
        jPanel5.add(jPanel8);
        
        DatabaseInitializationPane.add(jPanel5);
        
        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jLabel7.setText("Database Name: ");
        jPanel10.add(jLabel7);
        
        jTextField1.setEditable(false);
        jTextField1.setText("nvc");
        jTextField1.setBackground(java.awt.Color.pink);
        jTextField1.setPreferredSize(new java.awt.Dimension(200, 17));
        jTextField1.setMinimumSize(new java.awt.Dimension(200, 17));
        jPanel10.add(jTextField1);
        
        createDatabaseButton.setText("Create Database");
        createDatabaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDatabaseButtonActionPerformed(evt);
            }
        });
        
        jPanel10.add(createDatabaseButton);
        
        DatabaseInitializationPane.add(jPanel10);
        
        jTabbedPane2.addTab("Database Initialization", DatabaseInitializationPane);
        
        DatabaseStartupPane.setLayout(new javax.swing.BoxLayout(DatabaseStartupPane, javax.swing.BoxLayout.Y_AXIS));
        
        startupPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        startupPane.setPreferredSize(new java.awt.Dimension(232, 33));
        startupPane.setMinimumSize(new java.awt.Dimension(232, 33));
        startupPane.setMaximumSize(new java.awt.Dimension(32767, 33));
        jLabel4.setText("Database Startup");
        startupPane.add(jLabel4);
        
        databaseStartupButton.setText("start");
        databaseStartupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databaseStartupButtonActionPerformed(evt);
            }
        });
        
        startupPane.add(databaseStartupButton);
        
        DatabaseStartupPane.add(startupPane);
        
        shutdownPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jLabel5.setText("Database Shutdown");
        shutdownPane.add(jLabel5);
        
        databaseShutdownButton.setText("stop");
        databaseShutdownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databaseShutdownButtonActionPerformed(evt);
            }
        });
        
        shutdownPane.add(databaseShutdownButton);
        
        DatabaseStartupPane.add(shutdownPane);
        
        jTabbedPane2.addTab("Database Startup", DatabaseStartupPane);
        
        DatabaseTablesPane.setLayout(new javax.swing.BoxLayout(DatabaseTablesPane, javax.swing.BoxLayout.Y_AXIS));
        
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jPanel4.setPreferredSize(new java.awt.Dimension(232, 33));
        jPanel4.setMinimumSize(new java.awt.Dimension(232, 33));
        jPanel4.setMaximumSize(new java.awt.Dimension(32767, 33));
        jLabel3.setText("Create Base Tables:");
        jPanel4.add(jLabel3);
        
        createBaseTablesButton.setText("run");
        createBaseTablesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBaseTablesButtonActionPerformed(evt);
            }
        });
        
        jPanel4.add(createBaseTablesButton);
        
        DatabaseTablesPane.add(jPanel4);
        
        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jLabel6.setText("Create Summary Tables:");
        jPanel9.add(jLabel6);
        
        createSummaryTables.setText("run");
        createSummaryTables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSummaryTablesActionPerformed(evt);
            }
        });
        
        jPanel9.add(createSummaryTables);
        
        DatabaseTablesPane.add(jPanel9);
        
        jTabbedPane2.addTab("Database Tables", DatabaseTablesPane);
        
        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jLabel8.setText("User Name:");
        jPanel11.add(jLabel8);
        
        jTextField2.setEditable(false);
        jTextField2.setText("datauser");
        jTextField2.setBackground(java.awt.Color.pink);
        jTextField2.setPreferredSize(new java.awt.Dimension(200, 17));
        jTextField2.setMinimumSize(new java.awt.Dimension(200, 17));
        jPanel11.add(jTextField2);
        
        createUserButton.setText("Create User");
        createUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserButtonActionPerformed(evt);
            }
        });
        
        jPanel11.add(createUserButton);
        
        DatabaseUsersPane.add(jPanel11);
        
        jTabbedPane2.addTab("Database Users", DatabaseUsersPane);
        
        getContentPane().add(jTabbedPane2, java.awt.BorderLayout.CENTER);
        
        pack();
    }//GEN-END:initComponents

    private void createDatabaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDatabaseButtonActionPerformed
        // Add your handling code here:
        manager.createDatabase();
    }//GEN-LAST:event_createDatabaseButtonActionPerformed

    private void createUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserButtonActionPerformed
        // Add your handling code here:
        manager.createUser();
    }//GEN-LAST:event_createUserButtonActionPerformed

    private void createSummaryTablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSummaryTablesActionPerformed
        // Add your handling code here:
        manager.createSummaryTables();
    }//GEN-LAST:event_createSummaryTablesActionPerformed

    private void createBaseTablesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBaseTablesButtonActionPerformed
        // Add your handling code here:
        manager.createBaseTables();
    }//GEN-LAST:event_createBaseTablesButtonActionPerformed

    private void databaseShutdownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databaseShutdownButtonActionPerformed
        // Add your handling code here:
        manager.stopDatabase();
    }//GEN-LAST:event_databaseShutdownButtonActionPerformed

    private void databaseStartupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databaseStartupButtonActionPerformed
        // Add your handling code here:
        manager.startDatabase();
        
    }//GEN-LAST:event_databaseStartupButtonActionPerformed

    private void initializeDatabaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initializeDatabaseButtonActionPerformed
        // Add your handling code here:
        manager.initDatabase();
    }//GEN-LAST:event_initializeDatabaseButtonActionPerformed

    private void chooseInitDirectoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseInitDirectoryButtonActionPerformed
        // Add your handling code here:
        String directory = framework.directoryChooser();
        if ( directory == null)
        {
            framework.debug( 0, "not a valid directory selection" );
        }
        else
        {
            initDirectoryTextField.setText( directory );
            
        }
    }//GEN-LAST:event_chooseInitDirectoryButtonActionPerformed

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        this.dispose();
        //System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        new DatabaseManagerInterface().show();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel DatabaseInitializationPane;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField osTypeTextField;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField rdbmsTypeTextField;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton chooseInitDirectoryButton;
    private javax.swing.JTextField initDirectoryTextField;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton initializeDatabaseButton;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton createDatabaseButton;
    private javax.swing.JPanel DatabaseStartupPane;
    private javax.swing.JPanel startupPane;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton databaseStartupButton;
    private javax.swing.JPanel shutdownPane;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton databaseShutdownButton;
    private javax.swing.JPanel DatabaseTablesPane;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton createBaseTablesButton;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton createSummaryTables;
    private javax.swing.JPanel DatabaseUsersPane;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton createUserButton;
    // End of variables declaration//GEN-END:variables

}
