/**
 *
 * @author @author@ 
 * @version @release@ 
 *
 *     '$Author: harris $'
 *     '$Date: 2001-10-10 18:12:42 $'
 *     '$Revision: 1.1 $'
 */
 
package vegclient.framework;

import javax.swing.*;

import vegclient.framework.*;

public class NewDataLoader extends javax.swing.JFrame {

    
   private ProjectManager manager = new ProjectManager();
   //the strata methods
   String[] strataMethods = {
                       "TNC",
                       "European"};
 
   String[] tncCodes = {"t1", "t2", "t3", "s1", "s2", "s3", "h", "n", "v", "e"};
   
    /** Creates new form NewDataLoader */
    public NewDataLoader() {
        initComponents();
        setSize(520, 600);
        setTitle("New Plot Data -- Form Loader build: @release@");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        buttonGroup1 = new javax.swing.ButtonGroup();
        mainTabbedPane = new javax.swing.JTabbedPane();
        projectPanel = new javax.swing.JPanel();
        projectChooserPane = new javax.swing.JPanel();
        initilizeNewProjectPane = new javax.swing.JPanel();
        initializeNewProjectRadio = new javax.swing.JRadioButton();
        workWithLastProjectPane = new javax.swing.JPanel();
        workWithLastProjectRadio = new javax.swing.JRadioButton();
        projectMainPane = new javax.swing.JPanel();
        projectDescriptionPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        projectDescriptionTextField = new javax.swing.JTextField();
        jList6 = new javax.swing.JList();
        projectNamePane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        projectNameTextField = new javax.swing.JTextField();
        projectFilePane = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        projectFileTextField = new javax.swing.JTextField();
        projectPlotsSelectionPane = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        selectablePlotsList = new javax.swing.JList();
        projectAuthorPane = new javax.swing.JPanel();
        authorLabelPane = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        authorNamePanel = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox();
        plotPanel = new javax.swing.JPanel();
        plotMainPane = new javax.swing.JPanel();
        plotCodePane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        plotStatePane = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        plotCountryPane = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        plotCountyPane = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        plotUSGSQuadPane = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        plotLatitudePane = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        plotLongitudePane = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        plotDatumPane = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        observationPane = new javax.swing.JPanel();
        observationMainPane = new javax.swing.JPanel();
        observationStartDate = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        observationStopDate = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        observationSoilType = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        observationSoilDepth = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        observationSoilDepthRange = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        observationPercentRock = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        observationPercentOrganic = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        observationPercentWater = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        strataPane = new javax.swing.JPanel();
        strataMainPane = new javax.swing.JPanel();
        strataMethodPane = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        staratamethodComboBox = new JComboBox(strataMethods);
        strataDescriptionPane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        strataDescriptionPanel = new javax.swing.JTable();
        plantTaxonomyPane = new javax.swing.JPanel();
        plantNamePanel = new javax.swing.JPanel();
        plantNameLabel = new javax.swing.JLabel();
        plantNameTextField = new javax.swing.JTextField();
        strataCompositionPane = new javax.swing.JPanel();
        individualStrataPane = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        strataCompostionCodeComboBox = new JComboBox(tncCodes);
        jLabel23 = new javax.swing.JLabel();
        strataCoverValueTextField = new javax.swing.JTextField();
        cumStrataPane = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        strataCompositionOptionspane = new javax.swing.JPanel();
        newPlantSelectorButton = new javax.swing.JButton();
        updateSelectorButton = new javax.swing.JButton();
        
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        
        mainTabbedPane.setFont(new java.awt.Font("Default", 0, 12));
        projectPanel.setLayout(new javax.swing.BoxLayout(projectPanel, javax.swing.BoxLayout.Y_AXIS));
        
        projectPanel.setForeground(java.awt.Color.blue);
        projectChooserPane.setLayout(new javax.swing.BoxLayout(projectChooserPane, javax.swing.BoxLayout.Y_AXIS));
        
        projectChooserPane.setBorder(new javax.swing.border.EtchedBorder());
        projectChooserPane.setForeground(java.awt.Color.lightGray);
        projectChooserPane.setPreferredSize(new java.awt.Dimension(199, 70));
        projectChooserPane.setMinimumSize(new java.awt.Dimension(199, 70));
        projectChooserPane.setMaximumSize(new java.awt.Dimension(32771, 70));
        initilizeNewProjectPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        initializeNewProjectRadio.setForeground(java.awt.Color.blue);
        initializeNewProjectRadio.setFont(new java.awt.Font("Default", 0, 12));
        initializeNewProjectRadio.setText("Intitialize New Project:");
        initilizeNewProjectPane.add(initializeNewProjectRadio);
        
        projectChooserPane.add(initilizeNewProjectPane);
        
        workWithLastProjectPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        workWithLastProjectRadio.setForeground(java.awt.Color.blue);
        workWithLastProjectRadio.setFont(new java.awt.Font("Default", 0, 12));
        workWithLastProjectRadio.setText("Work With Last Project:");
        workWithLastProjectRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workWithLastProjectRadioActionPerformed(evt);
            }
        });
        
        workWithLastProjectPane.add(workWithLastProjectRadio);
        
        projectChooserPane.add(workWithLastProjectPane);
        
        projectPanel.add(projectChooserPane);
        
        projectMainPane.setLayout(new javax.swing.BoxLayout(projectMainPane, javax.swing.BoxLayout.Y_AXIS));
        
        projectDescriptionPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        projectDescriptionPane.setMaximumSize(new java.awt.Dimension(32767, 27));
        jLabel2.setText("Project Description");
        jLabel2.setForeground(java.awt.Color.blue);
        jLabel2.setFont(new java.awt.Font("Default", 0, 12));
        projectDescriptionPane.add(jLabel2);
        
        projectDescriptionTextField.setBackground(java.awt.Color.pink);
        projectDescriptionTextField.setPreferredSize(new java.awt.Dimension(200, 17));
        projectDescriptionPane.add(projectDescriptionTextField);
        
        projectDescriptionPane.add(jList6);
        
        projectMainPane.add(projectDescriptionPane);
        
        projectNamePane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        projectNamePane.setMaximumSize(new java.awt.Dimension(32767, 27));
        jLabel1.setText("ProjectName: ");
        jLabel1.setForeground(java.awt.Color.blue);
        jLabel1.setFont(new java.awt.Font("Default", 0, 12));
        projectNamePane.add(jLabel1);
        
        projectNameTextField.setBackground(java.awt.Color.pink);
        projectNameTextField.setPreferredSize(new java.awt.Dimension(200, 17));
        projectNamePane.add(projectNameTextField);
        
        projectMainPane.add(projectNamePane);
        
        projectFilePane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        projectFilePane.setPreferredSize(new java.awt.Dimension(288, 40));
        projectFilePane.setMinimumSize(new java.awt.Dimension(92, 40));
        projectFilePane.setMaximumSize(new java.awt.Dimension(32767, 40));
        jLabel19.setText("Project File:");
        jLabel19.setForeground(java.awt.Color.blue);
        jLabel19.setFont(new java.awt.Font("Default", 0, 12));
        projectFilePane.add(jLabel19);
        
        projectFileTextField.setBackground(java.awt.Color.pink);
        projectFileTextField.setPreferredSize(new java.awt.Dimension(200, 17));
        projectFilePane.add(projectFileTextField);
        
        projectMainPane.add(projectFilePane);
        
        projectPlotsSelectionPane.setLayout(new javax.swing.BoxLayout(projectPlotsSelectionPane, javax.swing.BoxLayout.X_AXIS));
        
        projectPlotsSelectionPane.setPreferredSize(new java.awt.Dimension(250, 120));
        projectPlotsSelectionPane.setMaximumSize(new java.awt.Dimension(250, 120));
        jScrollPane3.setViewportView(selectablePlotsList);
        
        projectPlotsSelectionPane.add(jScrollPane3);
        
        projectMainPane.add(projectPlotsSelectionPane);
        
        projectAuthorPane.setLayout(new javax.swing.BoxLayout(projectAuthorPane, javax.swing.BoxLayout.Y_AXIS));
        
        projectAuthorPane.setMaximumSize(new java.awt.Dimension(32767, 27));
        jLabel24.setText("Project Author");
        jLabel24.setForeground(java.awt.Color.blue);
        jLabel24.setFont(new java.awt.Font("Default", 0, 12));
        authorLabelPane.add(jLabel24);
        
        projectAuthorPane.add(authorLabelPane);
        
        authorNamePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jLabel25.setText("First Name: ");
        authorNamePanel.add(jLabel25);
        
        jTextField19.setBackground(java.awt.Color.pink);
        jTextField19.setPreferredSize(new java.awt.Dimension(100, 17));
        authorNamePanel.add(jTextField19);
        
        jLabel26.setText("Last Name: ");
        authorNamePanel.add(jLabel26);
        
        jTextField20.setBackground(java.awt.Color.pink);
        jTextField20.setPreferredSize(new java.awt.Dimension(100, 17));
        authorNamePanel.add(jTextField20);
        
        jLabel27.setText("Role: ");
        authorNamePanel.add(jLabel27);
        
        jComboBox7.setBackground(java.awt.Color.pink);
        jComboBox7.setPreferredSize(new java.awt.Dimension(40, 22));
        jComboBox7.setMinimumSize(new java.awt.Dimension(40, 22));
        authorNamePanel.add(jComboBox7);
        
        projectAuthorPane.add(authorNamePanel);
        
        projectMainPane.add(projectAuthorPane);
        
        projectPanel.add(projectMainPane);
        
        mainTabbedPane.addTab("Project", projectPanel);
        
        plotPanel.setLayout(new java.awt.BorderLayout());
        
        plotMainPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        plotCodePane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jLabel3.setText("Plot Code: ");
        jLabel3.setForeground(java.awt.Color.blue);
        jLabel3.setFont(new java.awt.Font("Default", 0, 12));
        plotCodePane.add(jLabel3);
        
        jTextField3.setBackground(java.awt.Color.pink);
        jTextField3.setPreferredSize(new java.awt.Dimension(200, 17));
        plotCodePane.add(jTextField3);
        
        plotMainPane.add(plotCodePane);
        
        plotStatePane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jLabel4.setText("State: ");
        jLabel4.setForeground(java.awt.Color.blue);
        jLabel4.setFont(new java.awt.Font("Default", 0, 12));
        plotStatePane.add(jLabel4);
        
        jTextField4.setBackground(java.awt.Color.pink);
        jTextField4.setPreferredSize(new java.awt.Dimension(200, 17));
        plotStatePane.add(jTextField4);
        
        plotMainPane.add(plotStatePane);
        
        plotCountryPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jLabel5.setText("Country: ");
        jLabel5.setForeground(java.awt.Color.blue);
        jLabel5.setFont(new java.awt.Font("Default", 0, 12));
        plotCountryPane.add(jLabel5);
        
        jTextField5.setBackground(java.awt.Color.pink);
        jTextField5.setPreferredSize(new java.awt.Dimension(200, 17));
        plotCountryPane.add(jTextField5);
        
        plotMainPane.add(plotCountryPane);
        
        plotCountyPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jLabel6.setText("County: ");
        jLabel6.setForeground(java.awt.Color.blue);
        jLabel6.setFont(new java.awt.Font("Default", 0, 12));
        plotCountyPane.add(jLabel6);
        
        jTextField6.setBackground(java.awt.Color.pink);
        jTextField6.setPreferredSize(new java.awt.Dimension(200, 17));
        plotCountyPane.add(jTextField6);
        
        plotMainPane.add(plotCountyPane);
        
        plotUSGSQuadPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jLabel7.setText("USGS Quad:");
        jLabel7.setForeground(java.awt.Color.blue);
        jLabel7.setFont(new java.awt.Font("Default", 0, 12));
        plotUSGSQuadPane.add(jLabel7);
        
        jTextField7.setBackground(java.awt.Color.pink);
        jTextField7.setPreferredSize(new java.awt.Dimension(200, 17));
        plotUSGSQuadPane.add(jTextField7);
        
        plotMainPane.add(plotUSGSQuadPane);
        
        plotLatitudePane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jLabel8.setText("Latitude: ");
        jLabel8.setForeground(java.awt.Color.blue);
        jLabel8.setFont(new java.awt.Font("Default", 0, 12));
        plotLatitudePane.add(jLabel8);
        
        jTextField8.setBackground(java.awt.Color.pink);
        jTextField8.setPreferredSize(new java.awt.Dimension(200, 17));
        plotLatitudePane.add(jTextField8);
        
        plotMainPane.add(plotLatitudePane);
        
        plotLongitudePane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jLabel9.setText("Longitude: ");
        jLabel9.setForeground(java.awt.Color.blue);
        jLabel9.setFont(new java.awt.Font("Default", 0, 12));
        plotLongitudePane.add(jLabel9);
        
        jTextField9.setBackground(java.awt.Color.pink);
        jTextField9.setPreferredSize(new java.awt.Dimension(200, 17));
        plotLongitudePane.add(jTextField9);
        
        plotMainPane.add(plotLongitudePane);
        
        plotDatumPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jLabel10.setText("Datum: ");
        jLabel10.setForeground(java.awt.Color.blue);
        jLabel10.setFont(new java.awt.Font("Default", 0, 12));
        plotDatumPane.add(jLabel10);
        
        jTextField10.setBackground(java.awt.Color.pink);
        jTextField10.setPreferredSize(new java.awt.Dimension(200, 17));
        plotDatumPane.add(jTextField10);
        
        plotMainPane.add(plotDatumPane);
        
        plotPanel.add(plotMainPane, java.awt.BorderLayout.CENTER);
        
        mainTabbedPane.addTab("Plot", plotPanel);
        
        observationPane.setLayout(new java.awt.BorderLayout());
        
        observationMainPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        observationStartDate.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jLabel11.setText("Start Date:");
        jLabel11.setForeground(java.awt.Color.blue);
        jLabel11.setFont(new java.awt.Font("Default", 0, 12));
        observationStartDate.add(jLabel11);
        
        jTextField11.setBackground(java.awt.Color.pink);
        jTextField11.setPreferredSize(new java.awt.Dimension(200, 17));
        observationStartDate.add(jTextField11);
        
        observationMainPane.add(observationStartDate);
        
        observationStopDate.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jLabel12.setText("Stop Date:");
        jLabel12.setForeground(java.awt.Color.blue);
        jLabel12.setFont(new java.awt.Font("Default", 0, 12));
        observationStopDate.add(jLabel12);
        
        jTextField12.setBackground(java.awt.Color.pink);
        jTextField12.setPreferredSize(new java.awt.Dimension(200, 17));
        observationStopDate.add(jTextField12);
        
        observationMainPane.add(observationStopDate);
        
        observationSoilType.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jLabel13.setText("Soil Type:");
        jLabel13.setForeground(java.awt.Color.blue);
        jLabel13.setFont(new java.awt.Font("Default", 0, 12));
        observationSoilType.add(jLabel13);
        
        jTextField13.setBackground(java.awt.Color.pink);
        jTextField13.setPreferredSize(new java.awt.Dimension(200, 17));
        observationSoilType.add(jTextField13);
        
        observationMainPane.add(observationSoilType);
        
        observationSoilDepth.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jLabel14.setText("Soil Depth: ");
        jLabel14.setForeground(java.awt.Color.blue);
        jLabel14.setFont(new java.awt.Font("Default", 0, 12));
        observationSoilDepth.add(jLabel14);
        
        jTextField14.setBackground(java.awt.Color.pink);
        jTextField14.setPreferredSize(new java.awt.Dimension(200, 17));
        observationSoilDepth.add(jTextField14);
        
        observationMainPane.add(observationSoilDepth);
        
        observationSoilDepthRange.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jLabel15.setText("Soil Depth Range");
        jLabel15.setForeground(java.awt.Color.blue);
        jLabel15.setFont(new java.awt.Font("Default", 0, 12));
        observationSoilDepthRange.add(jLabel15);
        
        jTextField15.setBackground(java.awt.Color.pink);
        jTextField15.setPreferredSize(new java.awt.Dimension(200, 17));
        observationSoilDepthRange.add(jTextField15);
        
        observationMainPane.add(observationSoilDepthRange);
        
        observationPercentRock.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jLabel16.setText("Percent Rock: ");
        jLabel16.setForeground(java.awt.Color.blue);
        jLabel16.setFont(new java.awt.Font("Default", 0, 12));
        observationPercentRock.add(jLabel16);
        
        jTextField16.setBackground(java.awt.Color.pink);
        jTextField16.setPreferredSize(new java.awt.Dimension(200, 17));
        observationPercentRock.add(jTextField16);
        
        observationMainPane.add(observationPercentRock);
        
        observationPercentOrganic.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jLabel17.setText("Percent Organic Material");
        jLabel17.setForeground(java.awt.Color.blue);
        jLabel17.setFont(new java.awt.Font("Default", 0, 12));
        observationPercentOrganic.add(jLabel17);
        
        jTextField17.setBackground(java.awt.Color.pink);
        jTextField17.setPreferredSize(new java.awt.Dimension(200, 17));
        observationPercentOrganic.add(jTextField17);
        
        observationMainPane.add(observationPercentOrganic);
        
        observationPercentWater.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jLabel18.setText("Percent Water: ");
        jLabel18.setForeground(java.awt.Color.blue);
        jLabel18.setFont(new java.awt.Font("Default", 0, 12));
        observationPercentWater.add(jLabel18);
        
        jTextField18.setBackground(java.awt.Color.pink);
        jTextField18.setPreferredSize(new java.awt.Dimension(200, 17));
        observationPercentWater.add(jTextField18);
        
        observationMainPane.add(observationPercentWater);
        
        observationPane.add(observationMainPane, java.awt.BorderLayout.CENTER);
        
        mainTabbedPane.addTab("Observations", observationPane);
        
        strataPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        strataMainPane.setLayout(new javax.swing.BoxLayout(strataMainPane, javax.swing.BoxLayout.Y_AXIS));
        
        jLabel20.setText("Enter a Strata method or pick from the list:");
        jLabel20.setForeground(java.awt.Color.blue);
        jLabel20.setFont(new java.awt.Font("Default", 0, 12));
        strataMethodPane.add(jLabel20);
        
        staratamethodComboBox.setForeground(java.awt.Color.blue);
        staratamethodComboBox.setBackground(java.awt.Color.pink);
        staratamethodComboBox.setEditable(true);
        staratamethodComboBox.setFont(new java.awt.Font("Default", 0, 12));
        strataMethodPane.add(staratamethodComboBox);
        
        strataMainPane.add(strataMethodPane);
        
        strataDescriptionPanel.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {"t1", "Emergent", "", ""},
            {"t2", "Canopy", null, null},
            {"t3", "Sub-Canopy", null, null},
            {"s1", "Tall-Shrub", null, null},
            {"s2", "Short-Shrub", null, null},
            {"s3", "Drawrf-Shrub", null, null},
            {"H", "Herbaceous", null, null},
            {"N", "Non-Vascular", null, null},
            {"V", "Vine/Liana", null, null},
            {"E", "Epiphyte", null, null},
            {null, null, null, null}
        },
        new String [] {
            "code", "name", "height", "cover"
        }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };
            
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
            
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(strataDescriptionPanel);
        
        strataDescriptionPane.add(jScrollPane1);
        
        strataMainPane.add(strataDescriptionPane);
        
        strataPane.add(strataMainPane);
        
        mainTabbedPane.addTab("Strata", strataPane);
        
        plantTaxonomyPane.setLayout(new javax.swing.BoxLayout(plantTaxonomyPane, javax.swing.BoxLayout.Y_AXIS));
        
        plantNamePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        plantNamePanel.setMaximumSize(new java.awt.Dimension(40000, 60));
        plantNameLabel.setText("Plant Name:");
        plantNameLabel.setForeground(java.awt.Color.blue);
        plantNameLabel.setFont(new java.awt.Font("Default", 0, 12));
        plantNamePanel.add(plantNameLabel);
        
        plantNameTextField.setBackground(java.awt.Color.pink);
        plantNameTextField.setPreferredSize(new java.awt.Dimension(300, 17));
        plantNameTextField.setMinimumSize(new java.awt.Dimension(120, 17));
        plantNamePanel.add(plantNameTextField);
        
        plantTaxonomyPane.add(plantNamePanel);
        
        strataCompositionPane.setLayout(new javax.swing.BoxLayout(strataCompositionPane, javax.swing.BoxLayout.Y_AXIS));
        
        strataCompositionPane.setMaximumSize(new java.awt.Dimension(32767, 120));
        individualStrataPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jLabel21.setText("Strata Code: ");
        jLabel21.setForeground(java.awt.Color.blue);
        jLabel21.setFont(new java.awt.Font("Default", 0, 12));
        individualStrataPane.add(jLabel21);
        
        strataCompostionCodeComboBox.setBackground(java.awt.Color.pink);
        individualStrataPane.add(strataCompostionCodeComboBox);
        
        jLabel23.setText("   Cover Value:   ");
        jLabel23.setForeground(java.awt.Color.blue);
        jLabel23.setFont(new java.awt.Font("Default", 0, 12));
        individualStrataPane.add(jLabel23);
        
        strataCoverValueTextField.setBackground(java.awt.Color.pink);
        strataCoverValueTextField.setPreferredSize(new java.awt.Dimension(40, 17));
        strataCoverValueTextField.setMinimumSize(new java.awt.Dimension(40, 17));
        individualStrataPane.add(strataCoverValueTextField);
        
        strataCompositionPane.add(individualStrataPane);
        
        cumStrataPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jLabel22.setText("Cumulative Strata Cover: ");
        jLabel22.setForeground(java.awt.Color.blue);
        jLabel22.setFont(new java.awt.Font("Default", 0, 12));
        cumStrataPane.add(jLabel22);
        
        jTextField2.setBackground(java.awt.Color.pink);
        jTextField2.setPreferredSize(new java.awt.Dimension(40, 17));
        jTextField2.setMinimumSize(new java.awt.Dimension(40, 17));
        cumStrataPane.add(jTextField2);
        
        strataCompositionPane.add(cumStrataPane);
        
        plantTaxonomyPane.add(strataCompositionPane);
        
        strataCompositionOptionspane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 12));
        
        newPlantSelectorButton.setForeground(java.awt.Color.blue);
        newPlantSelectorButton.setFont(new java.awt.Font("Default", 0, 12));
        newPlantSelectorButton.setText("New Record");
        strataCompositionOptionspane.add(newPlantSelectorButton);
        
        updateSelectorButton.setForeground(java.awt.Color.blue);
        updateSelectorButton.setFont(new java.awt.Font("Default", 0, 12));
        updateSelectorButton.setText("Save Current Record");
        strataCompositionOptionspane.add(updateSelectorButton);
        
        plantTaxonomyPane.add(strataCompositionOptionspane);
        
        mainTabbedPane.addTab("Plant Cover", plantTaxonomyPane);
        
        getContentPane().add(mainTabbedPane, java.awt.BorderLayout.CENTER);
        
        pack();
    }//GEN-END:initComponents
    /**
     * this method is activated when the work with last project radio button is selected
     * and will update all the fields in the form with the information stored in the last 
     * project xml file
     */
    private void workWithLastProjectRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workWithLastProjectRadioActionPerformed
        // Add your handling code here:
        System.out.println("working with last known Project");
        updateProjectForm("yelp.xml");
    }//GEN-LAST:event_workWithLastProjectRadioActionPerformed
    /**
     * this method uses the project and plot class and the xml parsers to update this
     * form's values from a input project xml file
     *
     * @param fileName -- the name of the file to be used for updating the form
     *
     */
    private void updateProjectForm(String fileName)
    {
        try
        {
            VegProject project = new VegProject(fileName);
            //update the fields painfully
            projectDescriptionTextField.setText( project.getProjectDescription() );
            projectNameTextField.setText( project.getProjectName() );
            projectFileTextField.setText( fileName );
            
             //selectablePlotsVector.removeAllElements();
             selectablePlotsList.setListData( project.getPlotNames()  );
             selectablePlotsList.validate();
        
            
            
        }
        catch (Exception e)
        {
            manager.debug(0, e.getMessage() );
        }
    }
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        //System.exit(1);
        this.dispose();
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        new NewDataLoader().show();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JPanel projectPanel;
    private javax.swing.JPanel projectChooserPane;
    private javax.swing.JPanel initilizeNewProjectPane;
    private javax.swing.JRadioButton initializeNewProjectRadio;
    private javax.swing.JPanel workWithLastProjectPane;
    private javax.swing.JRadioButton workWithLastProjectRadio;
    private javax.swing.JPanel projectMainPane;
    private javax.swing.JPanel projectDescriptionPane;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField projectDescriptionTextField;
    private javax.swing.JList jList6;
    private javax.swing.JPanel projectNamePane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField projectNameTextField;
    private javax.swing.JPanel projectFilePane;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JTextField projectFileTextField;
    private javax.swing.JPanel projectPlotsSelectionPane;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList selectablePlotsList;
    private javax.swing.JPanel projectAuthorPane;
    private javax.swing.JPanel authorLabelPane;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel authorNamePanel;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JPanel plotPanel;
    private javax.swing.JPanel plotMainPane;
    private javax.swing.JPanel plotCodePane;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel plotStatePane;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel plotCountryPane;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JPanel plotCountyPane;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JPanel plotUSGSQuadPane;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JPanel plotLatitudePane;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JPanel plotLongitudePane;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel plotDatumPane;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JPanel observationPane;
    private javax.swing.JPanel observationMainPane;
    private javax.swing.JPanel observationStartDate;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JPanel observationStopDate;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JPanel observationSoilType;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JPanel observationSoilDepth;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JPanel observationSoilDepthRange;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JPanel observationPercentRock;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JPanel observationPercentOrganic;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JPanel observationPercentWater;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JPanel strataPane;
    private javax.swing.JPanel strataMainPane;
    private javax.swing.JPanel strataMethodPane;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JComboBox staratamethodComboBox;
    private javax.swing.JPanel strataDescriptionPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable strataDescriptionPanel;
    private javax.swing.JPanel plantTaxonomyPane;
    private javax.swing.JPanel plantNamePanel;
    private javax.swing.JLabel plantNameLabel;
    private javax.swing.JTextField plantNameTextField;
    private javax.swing.JPanel strataCompositionPane;
    private javax.swing.JPanel individualStrataPane;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JComboBox strataCompostionCodeComboBox;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JTextField strataCoverValueTextField;
    private javax.swing.JPanel cumStrataPane;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel strataCompositionOptionspane;
    private javax.swing.JButton newPlantSelectorButton;
    private javax.swing.JButton updateSelectorButton;
    // End of variables declaration//GEN-END:variables

}
