/*
 * ProgressMeterDisplay.java
 *
 * Created on September 17, 2001, 5:04 PM
 */


/**
 *
 * @author  harris
 * @version 
 */
public class ProgressMeterDisplay extends javax.swing.JFrame {

    /** Creates new form ProgressMeterDisplay */
    public ProgressMeterDisplay() {
        setSize(300, 50);
        initComponents ();
        pack ();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        mainPane = new javax.swing.JPanel();
        mainProgressBar = new javax.swing.JProgressBar();
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        }
        );
        
        
        mainProgressBar.setString("12%");
          mainPane.add(mainProgressBar);
          
          
        getContentPane().add(mainPane, java.awt.BorderLayout.CENTER);
        
    }//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit (0);
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
    public static void main (String args[]) {
        new ProgressMeterDisplay ().show ();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPane;
    private javax.swing.JProgressBar mainProgressBar;
    // End of variables declaration//GEN-END:variables

}
