/**
 * SummaryViewerInterface.java
 *
 * Created on October 4, 2001, 11:10 AM
 *
 *
 *
 *  Authors: @author@
 *  Release: @release@
 *	
 *  '$Author: harris $'
 *  '$Date: 2001-10-10 18:12:43 $'
 * 	'$Revision: 1.1 $'
 */
package vegclient.framework;


import vegclient.framework.*;

public class SummaryViewerInterface extends javax.swing.JFrame {

    //utility classes
    ClientFramework framework = new ClientFramework();
    
    
    /** Creates new form SummaryViewerInterface */
    public SummaryViewerInterface() {
        initComponents();
        setSize(400, 120);
        setTitle("SummaryViewerInterface build:  @release@");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
            mainPane = new javax.swing.JPanel();
            selectionPane = new javax.swing.JPanel();
            jLabel1 = new javax.swing.JLabel();
            plotPackageFileTextField = new javax.swing.JTextField();
            fileChooserButton = new javax.swing.JButton();
            continuePane = new javax.swing.JPanel();
            continueButton = new javax.swing.JButton();
            
            getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));
            
            addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    exitForm(evt);
                }
            });
            
            mainPane.setLayout(new javax.swing.BoxLayout(mainPane, javax.swing.BoxLayout.Y_AXIS));
            
            selectionPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
            
            jLabel1.setText("Plot Package File");
            selectionPane.add(jLabel1);
            
            plotPackageFileTextField.setBackground(java.awt.Color.pink);
            plotPackageFileTextField.setPreferredSize(new java.awt.Dimension(140, 21));
            selectionPane.add(plotPackageFileTextField);
            
            fileChooserButton.setText("choose");
            fileChooserButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    fileChooserButtonActionPerformed(evt);
                }
            });
            
            selectionPane.add(fileChooserButton);
            
            mainPane.add(selectionPane);
          
          continueButton.setText("continue");
            continueButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    continueButtonActionPerformed(evt);
                }
            });
            
            continuePane.add(continueButton);
            
            mainPane.add(continuePane);
          
          getContentPane().add(mainPane);
        
        pack();
    }//GEN-END:initComponents

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        // Add your handling code here:
        StyleSheetInterface stylesheet = new StyleSheetInterface();
        stylesheet.show();
        
    }//GEN-LAST:event_continueButtonActionPerformed

    private void fileChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserButtonActionPerformed
        // Add your handling code here:
        String file = framework.fileChooser();
        if ( file != null )
        {
            plotPackageFileTextField.setText( file );
        }
        
    }//GEN-LAST:event_fileChooserButtonActionPerformed

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        new SummaryViewerInterface().show();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPane;
    private javax.swing.JPanel selectionPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField plotPackageFileTextField;
    private javax.swing.JButton fileChooserButton;
    private javax.swing.JPanel continuePane;
    private javax.swing.JButton continueButton;
    // End of variables declaration//GEN-END:variables

}
