/*
 * VegClassInstallerInterface.java
 *
 * Created on September 26, 2001, 11:44 AM
 */
package vegclient.installer;

/**
 *
 * @author  administrator
 * @version 
 */

import java.io.*;
import java.util.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;

import vegclient.installer.*;

public class VegClassInstallerInterface extends javax.swing.JFrame {

    private ClientFramework framework = new ClientFramework();
    private Installer install = new Installer();
    
    /** Creates new form VegClassInstallerInterface */
    public VegClassInstallerInterface() {
        initComponents ();
        pack ();
        setSize(380, 130);
        setTitle("Veg Package Installer - build: @release@");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        mainPane = new javax.swing.JPanel();
        installDirectoryPane = new javax.swing.JPanel();
        selectInstallDirectoryButton = new javax.swing.JButton();
        installDirectoryTextField = new javax.swing.JTextField();
        continuePane = new javax.swing.JPanel();
        continueButton = new javax.swing.JButton();
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        }
        );
        
        mainPane.setLayout(new javax.swing.BoxLayout(mainPane, 1));
        
        installDirectoryPane.setLayout(new java.awt.FlowLayout(0, 5, 5));
          
          selectInstallDirectoryButton.setText("Install Directory");
            selectInstallDirectoryButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    selectInstallDirectoryButtonActionPerformed(evt);
                }
            }
            );
            installDirectoryPane.add(selectInstallDirectoryButton);
            
            
          installDirectoryTextField.setPreferredSize(new java.awt.Dimension(200, 20));
            installDirectoryTextField.setBackground(java.awt.Color.pink);
            installDirectoryPane.add(installDirectoryTextField);
            
            mainPane.add(installDirectoryPane);
          
          
        continuePane.setLayout(new java.awt.FlowLayout(0, 5, 5));
          
          continueButton.setText("Continue");
            continueButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    continueButtonActionPerformed(evt);
                }
            }
            );
            continuePane.add(continueButton);
            
            mainPane.add(continuePane);
          
          
        getContentPane().add(mainPane);
        
    }//GEN-END:initComponents

  private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
// Add your handling code here:
      if ( ( installDirectoryTextField.getText() != null ) && ( installDirectoryTextField.getText().length() > 2 ) )
      {
          System.out.println("Installing the veg client in the directory: " + installDirectoryTextField.getText() );
          install.copyPackage( "vegClient", installDirectoryTextField.getText() );
          install.extractPackage("vegClient", installDirectoryTextField.getText() );
          framework.debug(0, "Install complete: run the vegclient.exe in: "+installDirectoryTextField.getText() );
          //close the window
          this.dispose();
      }
      else
      {
          framework.debug(0, "Not a valid install directory, please try again");
      }
  }//GEN-LAST:event_continueButtonActionPerformed

  private void selectInstallDirectoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectInstallDirectoryButtonActionPerformed
    // Add your handling code here:
      System.out.println("selecting the directory for installation of the veg database");
      String targetDirectory =  framework.directoryChooser();
      if ( targetDirectory != null)
      { 
          installDirectoryTextField.setText(targetDirectory.trim() );
      }
  }//GEN-LAST:event_selectInstallDirectoryButtonActionPerformed

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        //System.exit (0);
        this.dispose();
    }//GEN-LAST:event_exitForm

     		
   
    /**
    * @param args the command line arguments
    */
    public static void main (String args[]) {
        new VegClassInstallerInterface ().show ();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPane;
    private javax.swing.JPanel installDirectoryPane;
    private javax.swing.JButton selectInstallDirectoryButton;
    private javax.swing.JTextField installDirectoryTextField;
    private javax.swing.JPanel continuePane;
    private javax.swing.JButton continueButton;
    // End of variables declaration//GEN-END:variables

}
