/*
 * DataUpload.java
 *
 * Created on February 15, 2001, 3:04 PM
 */
import java.awt.*;
import java.awt.event.*;
import java.util.*;
import java.io.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.event.*;
import javax.swing.text.*;
import java.net.*; // For Socket stuff 

/**
 *  This class allows a user to either upload an xml document that contains plot 
 *  data, community data or plant data to the central server, where the data will
 *  be loaded to the appropriate database by the DBA/DA or this interface can be 
 *  used load the same categories of data to the 'client' database
 * 
 * @author  harris
 * @version 
 */
public class DataUpload extends javax.swing.JFrame {

    /** Creates new form DataUpload */
    public DataUpload() {
        initComponents ();
        pack ();
        setSize (400,410);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    public String inFile = null;
    private void initComponents() {//GEN-BEGIN:initComponents
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        upload = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jTextField2 = new javax.swing.JTextField();
        
        fileMenu.setText("File");
          
          openMenuItem.setText("Open");
            fileMenu.add(openMenuItem);
            
          saveMenuItem.setText("Save");
            fileMenu.add(saveMenuItem);
            
          saveAsMenuItem.setText("Save As ...");
            fileMenu.add(saveAsMenuItem);
            
          exitMenuItem.setText("Exit");
            exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    exitMenuItemActionPerformed(evt);
                }
            }
            );
            fileMenu.add(exitMenuItem);
            menuBar.add(fileMenu);
          
        editMenu.setText("Edit");
          
          cutMenuItem.setText("Cut");
            editMenu.add(cutMenuItem);
            
          copyMenuItem.setText("Copy");
            editMenu.add(copyMenuItem);
            
          pasteMenuItem.setText("Paste");
            editMenu.add(pasteMenuItem);
            
          deleteMenuItem.setText("Delete");
            editMenu.add(deleteMenuItem);
            menuBar.add(editMenu);
          
        helpMenu.setText("Help");
          
          contentsMenuItem.setText("Contents");
            helpMenu.add(contentsMenuItem);
            
          aboutMenuItem.setText("About");
            helpMenu.add(aboutMenuItem);
            menuBar.add(helpMenu);
          
        jMenu1.setText("Menu");
          jMenuBar1.add(jMenu1);
          
        jMenu2.setText("Menu");
          jMenuBar2.add(jMenu2);
          
        jMenu3.setText("Menu");
          jMenuBar3.add(jMenu3);
          getContentPane().setLayout(null);
        setTitle("Data Loader");
        setForeground(java.awt.Color.white);
        setResizable(false);
        setBackground(java.awt.Color.white);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        }
        );
        
        jButton1.setAlignmentY(0.6F);
        jButton1.setActionCommand("Input File");
        jButton1.setText("Input File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        }
        );
        
        getContentPane().add(jButton1);
        jButton1.setLocation(20, 10);
        jButton1.setSize(jButton1.getPreferredSize());
        
        
        jTextField1.setText(null);
        jTextField1.setBackground(java.awt.Color.pink);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        }
        );
        
        getContentPane().add(jTextField1);
        jTextField1.setBounds(140, 10, 230, 30);
        
        
        upload.setLabel("upload");
        upload.setText("UploadData");
        upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadActionPerformed(evt);
            }
        }
        );
        
        getContentPane().add(upload);
        upload.setLocation(10, 230);
        upload.setSize(upload.getPreferredSize());
        
        
        jRadioButton1.setText("jRadioButton1");
        
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(30, 80, -20, 230);
        
        
        jLabel1.setText("Data File Type");
        jLabel1.setFont(new java.awt.Font ("Dialog", 1, 14));
        
        getContentPane().add(jLabel1);
        jLabel1.setLocation(10, 70);
        jLabel1.setSize(jLabel1.getPreferredSize());
        
        
        jRadioButton2.setLabel("Well Curve");
        jRadioButton2.setText("Site Data");
        
        getContentPane().add(jRadioButton2);
        jRadioButton2.setLocation(10, 100);
        jRadioButton2.setSize(jRadioButton2.getPreferredSize());
        
        
        jRadioButton3.setText("Species Data");
        
        getContentPane().add(jRadioButton3);
        jRadioButton3.setLocation(140, 100);
        jRadioButton3.setSize(jRadioButton3.getPreferredSize());
        
        
        jRadioButton4.setText("Entire Plot");
        
        getContentPane().add(jRadioButton4);
        jRadioButton4.setLocation(290, 100);
        jRadioButton4.setSize(jRadioButton4.getPreferredSize());
        
        
        jLabel4.setText("Database to Load");
        jLabel4.setFont(new java.awt.Font ("Dialog", 1, 14));
        
        getContentPane().add(jLabel4);
        jLabel4.setLocation(10, 150);
        jLabel4.setSize(jLabel4.getPreferredSize());
        
        
        jCheckBox1.setText("Local");
        
        getContentPane().add(jCheckBox1);
        jCheckBox1.setLocation(40, 180);
        jCheckBox1.setSize(jCheckBox1.getPreferredSize());
        
        
        jCheckBox2.setText("Central Server");
        
        getContentPane().add(jCheckBox2);
        jCheckBox2.setLocation(210, 180);
        jCheckBox2.setSize(jCheckBox2.getPreferredSize());
        
        
        jTextField2.setText("Messages");
        jTextField2.setBackground(java.awt.Color.pink);
        
        getContentPane().add(jTextField2);
        jTextField2.setBounds(10, 280, 340, 30);
        
        setJMenuBar(menuBar);
        
        pack();
    }//GEN-END:initComponents

  private void uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadActionPerformed
// Add your handling code here:
      String databaseType=null;  //which database local or central
      String dataType = null; //the type of data file to be loaded
      
      System.out.println("test: ");
      
      //centralServer
      if (jCheckBox2.getSelectedObjects() != null) {
      //jCheckBox2.setSelected(true);
       databaseType="central";
      }
      
      //local database
      if (jCheckBox1.getSelectedObjects() != null) {
      databaseType="local";
      }
      
      //well curve
      if (jRadioButton2.getSelectedObjects() != null) {
      dataType="wellCurve";
      }
      
      //well curve
      if (jRadioButton3.getSelectedObjects() != null) {
      dataType="survey";
      }
      
      //well curve
      if (jRadioButton4.getSelectedObjects() != null) {
      dataType="horizon";
      }
      
      System.out.println("databaseType: "+databaseType);
      jTextField2.setText("databaseType: "+databaseType+" dataType: "+dataType);
      
      
     String servlet = ":8080/examples/servlet/DataExchangeServlet";
     String protocol = "http://";
     String host = "beta.nceas.ucsb.edu";
     String server = protocol + host + servlet;
     //String filename = "../test.dat";
     String parameterString = "?exchangeType=upload&submitter=harris&"
	  	+"password=jasmine&file=../test.dat";
         
      //call the method to upload the file to the database   
      DataExchangeClient dec = new DataExchangeClient();
	dec.uploadFile(servlet, protocol, host, server, inFile);
      
      
  }//GEN-LAST:event_uploadActionPerformed

  private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
// Add your handling code here:
  }//GEN-LAST:event_jTextField1ActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// //Add your handling code here:
      FileDialog d = new FileDialog(
	DataUpload.this,
	"what file do you want");
	d.setFile("*.*");
	d.setDirectory(".");
	d.show();
	String yourfile = "*.*";
	String yourdirectory = null;
        if ((yourfile = d.getFile()) != null) {
		yourdirectory = d.getDirectory();
		System.out.println(yourdirectory);
		jTextField1.setText(yourdirectory+yourfile);
                inFile = yourfile;
		}// end of if
	//else
	//textarea.setText("Which file?");
     
      
  }//GEN-LAST:event_jButton1ActionPerformed

    private void exitMenuItemActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit (0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit (0);
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
    public static void main (String args[]) {
        new DataUpload ().show () ;
        
        //Frame f = new DataUpload();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton upload;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
