/*
 * QueryModule.java
 *
 * Created on February 20, 2001, 8:39 AM by 
 */
import java.io.*;
import java.sql.*;
import java.text.*;
import java.util.*;

//import client.*;

/**
 * This class is an interface that allows a user to request data from the veg 
 * plot related servlets.  This query client will allow the user to develop a 
 * muti-component query using a number of predefined query elements including :
 * taxon name, community name, state, elevation etc.  Currently the class is 
 * just a skeleton -- used primarily for testing the client library -- and 
 * will change dramatically
 *
 * @author  John Harris
 * @version March 22, 2001
 */
public class QueryModule extends javax.swing.JFrame {

//make a string buffer to hold the results that are passed back
//from the DataRequestClient
StringBuffer results = new StringBuffer();
ResourceBundle rb = ResourceBundle.getBundle("interface");

    /** Creates new form QueryModule */
    public QueryModule() {
        initComponents ();
        setBackground(java.awt.Color.white);
        pack ();
        setSize(520,370);
       
    }
	
public void launchQueryModule(String action)
{

System.out.println("starting");
new QueryModule ().show ();


}
  

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
private void initComponents() {//GEN-BEGIN:initComponents
    menuBar = new javax.swing.JMenuBar();
    fileMenu = new javax.swing.JMenu();
    openMenuItem = new javax.swing.JMenuItem();
    saveMenuItem = new javax.swing.JMenuItem();
    saveAsMenuItem = new javax.swing.JMenuItem();
    exitMenuItem = new javax.swing.JMenuItem();
    editMenu = new javax.swing.JMenu();
    cutMenuItem = new javax.swing.JMenuItem();
    copyMenuItem = new javax.swing.JMenuItem();
    pasteMenuItem = new javax.swing.JMenuItem();
    deleteMenuItem = new javax.swing.JMenuItem();
    helpMenu = new javax.swing.JMenu();
    contentsMenuItem = new javax.swing.JMenuItem();
    aboutMenuItem = new javax.swing.JMenuItem();
    jLabel1 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jList2 = new javax.swing.JList();
    jLabel2 = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    jList3 = new javax.swing.JList();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jScrollPane7 = new javax.swing.JScrollPane();
    jList4 = new javax.swing.JList();
    jButton1 = new javax.swing.JButton();
    jTextField1 = new javax.swing.JTextField();
    jTextField2 = new javax.swing.JTextField();
    jRadioButton1 = new javax.swing.JRadioButton();
    jRadioButton2 = new javax.swing.JRadioButton();
    jScrollPane3 = new javax.swing.JScrollPane();
    jTextField3 = new javax.swing.JTextField();
    
    fileMenu.setText("File");
      
      openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);
        
      saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);
        
      saveAsMenuItem.setText("Save As ...");
        fileMenu.add(saveAsMenuItem);
        
      exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        }
        );
        fileMenu.add(exitMenuItem);
        menuBar.add(fileMenu);
      
    editMenu.setText("Edit");
      
      cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);
        
      copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);
        
      pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);
        
      deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);
        menuBar.add(editMenu);
      
    helpMenu.setText("Help");
      
      contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);
        
      aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);
        menuBar.add(helpMenu);
      getContentPane().setLayout(null);
    setTitle("Query Module Interface");
    setForeground(java.awt.Color.white);
    setBackground(java.awt.Color.white);
    addWindowListener(new java.awt.event.WindowAdapter() {
        public void windowClosing(java.awt.event.WindowEvent evt) {
            exitForm(evt);
        }
    }
    );
    
    jLabel1.setText("Desired Data Type");
    jLabel1.setFont(new java.awt.Font ("Dialog", 1, 11));
    
    getContentPane().add(jLabel1);
    jLabel1.setLocation(10, 30);
    jLabel1.setSize(jLabel1.getPreferredSize());
    
    
    
    jList2.setVisibleRowCount(6);
      String[] data = {"vegPlot", "community"};
      jList2.setListData(data);
      jScrollPane1.setViewportView(jList2);
      
      
    getContentPane().add(jScrollPane1);
    jScrollPane1.setBounds(140, 20, 130, 40);
    
    
    jLabel2.setText("Query Element");
    jLabel2.setFont(new java.awt.Font ("Dialog", 1, 11));
    
    getContentPane().add(jLabel2);
    jLabel2.setLocation(10, 90);
    jLabel2.setSize(jLabel2.getPreferredSize());
    
    
    
    String [] queryElements = {"taxon", "state", "minElevation", "maxElevation", "resultType", "communityName", "communityLevel" };
      jList3.setListData(queryElements);
      
      jScrollPane2.setViewportView(jList3);
      
      
    getContentPane().add(jScrollPane2);
    jScrollPane2.setBounds(110, 80, 110, 40);
    
    
    jLabel3.setText("Element Value");
    jLabel3.setFont(new java.awt.Font ("Dialog", 1, 11));
    
    getContentPane().add(jLabel3);
    jLabel3.setLocation(240, 90);
    jLabel3.setSize(jLabel3.getPreferredSize());
    
    
    jLabel4.setText("Query Element2");
    jLabel4.setFont(new java.awt.Font ("Dialog", 1, 11));
    
    getContentPane().add(jLabel4);
    jLabel4.setLocation(10, 140);
    jLabel4.setSize(jLabel4.getPreferredSize());
    
    
    jLabel5.setText("Element2 Value");
    jLabel5.setFont(new java.awt.Font ("Dialog", 1, 11));
    
    getContentPane().add(jLabel5);
    jLabel5.setLocation(240, 140);
    jLabel5.setSize(jLabel5.getPreferredSize());
    
    
    
    jList4.setListData(queryElements);
      jScrollPane7.setViewportView(jList4);
      
      
    getContentPane().add(jScrollPane7);
    jScrollPane7.setBounds(110, 130, 110, 40);
    
    
    jButton1.setText("Submit Query");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            submitQuery(evt);
        }
    }
    );
    
    getContentPane().add(jButton1);
    jButton1.setLocation(10, 190);
    jButton1.setSize(jButton1.getPreferredSize());
    
    
    jTextField1.setText("Fraxinus dipetala");
    jTextField1.setBackground(java.awt.Color.pink);
    
    getContentPane().add(jTextField1);
    jTextField1.setBounds(330, 80, 140, 30);
    
    
    jTextField2.setBackground(java.awt.Color.pink);
    
    getContentPane().add(jTextField2);
    jTextField2.setBounds(330, 130, 140, 30);
    
    
    jRadioButton1.setText("Local Database");
    jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jRadioButton1ActionPerformed(evt);
        }
    }
    );
    
    getContentPane().add(jRadioButton1);
    jRadioButton1.setLocation(330, 10);
    jRadioButton1.setSize(jRadioButton1.getPreferredSize());
    
    
    jRadioButton2.setText("Central Database");
    
    getContentPane().add(jRadioButton2);
    jRadioButton2.setLocation(330, 40);
    jRadioButton2.setSize(jRadioButton2.getPreferredSize());
    
    
    
    jTextField3.setText("Messages");
      jTextField3.setBackground(java.awt.Color.pink);
      jTextField3.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
              jTextField3ActionPerformed(evt);
          }
      }
      );
      jScrollPane3.setViewportView(jTextField3);
      
      
    getContentPane().add(jScrollPane3);
    jScrollPane3.setBounds(20, 240, 470, 60);
    
    setJMenuBar(menuBar);
    
}//GEN-END:initComponents

  private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
// Add your handling code here:
  }//GEN-LAST:event_jTextField3ActionPerformed

  private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
// Add your handling code here:
  }//GEN-LAST:event_jRadioButton1ActionPerformed


  
  private void submitQuery(java.awt.event.ActionEvent evt) 
	{//GEN-FIRST:event_submitQuery
   try {
   //get the properties out of the resource bundle
      String host=(rb.getString("requestparams.host"));
      String servlet=(rb.getString("requestparams.servlet"));
      String protocol=(rb.getString("requestparams.protocol"));
      
      // Add your handling code here:
      System.out.println("submittal button pressed");
      System.out.println("desiredDataType: "+jList2.getSelectedValue() );
      System.out.println("queryElement: "+jList3.getSelectedValue() +" "+jTextField1.getText());
      System.out.println("queryElement2: "+jList4.getSelectedValue()+" "+jTextField2.getText() );
      
      //make the parameters properties
      Properties parameters = new Properties();
      parameters.setProperty("requestDataType", jList2.getSelectedValue().toString().trim() );
      parameters.setProperty(jList3.getSelectedValue().toString().trim(), jTextField1.getText().trim() );
      parameters.setProperty("resultType", "summary" );
	
      
      //figure out whether the local or central database
      System.out.println("XXXX"+jRadioButton1.isSelected());
      
      //if this then the local database
      if (jRadioButton1.isSelected() == true ) {
        System.out.println("XXXX"+jRadioButton1.getText());
      
        try {
            
        //DataRequestClinet class to compose the query by developing 
        //a hash table containing the appropriate elements needed to 
        //be passed to the DataRequestHandler for local queries
        DataRequestClient drc = new DataRequestClient();
        drc.createQueryElementHash("taxon", jTextField1.getText().trim() );
        drc.createQueryElementHash("resultType", "summary" );
        drc.createQueryElementHash("requestDataType", "vegPlot" );
        
        //pass the above query element hashtable to the method that 
        //actually queries the local database
        drc.queryLocalDatabase(drc.queryElementHash); 
           
        //pass the results to the data viewer
        HtmlViewer hv = new HtmlViewer();
      	hv.show();
        hv.showData("summary.xml", "transformMultiPlotSummary.xsl", "text/html");
      }
      
      catch( Exception e ) {System.out.println("** failed in: QueryModule: "
	+" "+e.getMessage());}
      } //end if
      
      
      ///else if the central database  is selected 
      else  {
	try {
     	 //pass the input parameters to the DataRequestClient class
      	DataRequestClient drc = new DataRequestClient();
      
	  System.out.println("making the request");
	  jTextField3.setText("querying: "+host);
     	 //grab the data into a string
      	String returnedData=drc.requestURL(servlet, protocol, host, parameters);
      	System.out.println(returnedData);
      	jTextField3.setText(returnedData);
     

	System.out.println("showing the data");
	
      	//pass the dataString to the html viewer - soon the data will be xml
      	HtmlViewer hv = new HtmlViewer();
      	hv.show();
      	hv.showData(returnedData);
	  
	
	}
	 catch( Exception e ) {System.out.println("** failed in: "
	+" first try - anaylyzing the input parameters "+e.getMessage());}
      
      }	
      
   } //end major if
    catch( Exception e ) {System.out.println("** failed in: "
	+" first try - anaylyzing the input parameters "+e.getMessage());}
 
  
  }//GEN-LAST:event_submitQuery

    private void exitMenuItemActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit (0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit (0);
    }//GEN-LAST:event_exitForm

   
   
   
   /**
    * @param args the command line arguments
    */
///    public static void main (String args[]) {
public static void main (String args[]) {
        new QueryModule ().show ();
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList jList2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList jList3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JList jList4;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

}
