#
# Makefile for installer C code
# $Id: Makefile,v 1.1 2001-10-10 17:04:43 harris Exp $
#

GCC = gcc
GCC_FLAGS = -mno-cygwin
all:
	$(GCC) $(GCC_FLAGS) -o ./bin/start_installer.exe  ./src/start_installer.c
jar:
        

clean:
        

