/*
 * DataSourceClientViewerApplet.java
 *
 * Created on January 30, 2002, 8:27 PM
 */

/**
 *
 * @author  administrator
 */
public class DataSourceClientViewerApplet extends javax.swing.JApplet {

    /** Creates new form DataSourceClientViewerApplet */
    public DataSourceClientViewerApplet() 
    {
        initComponents();
        this.setSize(400,300);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
          jPanel1 = new javax.swing.JPanel();
          projectDescriptionTextArea = new javax.swing.JTextField();
          
          private javax.swing.JTextField projectDescriptionTextArea1;
          projectDescriptionTextArea.setToolTipText("help");
          projectDescriptionTextArea.setText("hdfgjsdf");
          projectDescriptionTextArea.setPreferredSize(new java.awt.Dimension(400, 21));
          projectDescriptionTextArea.setMinimumSize(new java.awt.Dimension(400, 21));
          jPanel1.add(projectDescriptionTextArea);
          
          getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField projectDescriptionTextArea;
    // End of variables declaration//GEN-END:variables

}
