import java.util.*;

/*
 * DataSourceClientApplet.java
 *
 * Created on January 29, 2002, 4:29 PM
 */

/**
 *
 * @author  administrator
 */
public class DataSourceClientApplet extends javax.swing.JApplet {
    private String server = "128.111.220.69";
    private DataSourceClient source = new DataSourceClient(server);
    private String targetPlot = null; //the plot of interest

    /** Creates new form DataSourceClientApplet */
    public DataSourceClientApplet() {
        initComponents();
        this.setSize(400,300);
        //this.setTitle("--Data Loader Applet--");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
              mainPane = new javax.swing.JPanel();
              jTabbedPane1 = new javax.swing.JTabbedPane();
              loginPanel = new javax.swing.JPanel();
              usernameLabel = new javax.swing.JLabel();
              loginNameTextArea = new javax.swing.JTextField();
              jLabel2 = new javax.swing.JLabel();
              loginPasswordTextArea = new javax.swing.JTextField();
              jPanel1 = new javax.swing.JPanel();
              loginButton = new javax.swing.JButton();
              jPanel3 = new javax.swing.JPanel();
              jScrollPane1 = new javax.swing.JScrollPane();
              choosablePlotsJlist = new javax.swing.JList();
              jPanel4 = new javax.swing.JPanel();
              projectNameTextArea = new javax.swing.JTextField();
              
              mainPane.setLayout(new javax.swing.BoxLayout(mainPane, javax.swing.BoxLayout.Y_AXIS));
              
              loginPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
              
              loginPanel.setMaximumSize(new java.awt.Dimension(32767, 32));
              usernameLabel.setText("email address:");
              loginPanel.add(usernameLabel);
              
              loginNameTextArea.setPreferredSize(new java.awt.Dimension(63, 21));
              loginPanel.add(loginNameTextArea);
              
              jLabel2.setText("password:");
              loginPanel.add(jLabel2);
              
              loginPasswordTextArea.setPreferredSize(new java.awt.Dimension(63, 21));
              loginPasswordTextArea.setMinimumSize(new java.awt.Dimension(63, 21));
              loginPanel.add(loginPasswordTextArea);
              
              jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
                
                jPanel1.setMaximumSize(new java.awt.Dimension(32767, 32));
                loginButton.setText("login");
                loginButton.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        loginButtonActionPerformed(evt);
                    }
                });
                
                jPanel1.add(loginButton);
                
                loginPanel.add(jPanel1);
              
              jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 220));
                  jScrollPane1.setMinimumSize(new java.awt.Dimension(500, 220));
                  choosablePlotsJlist.addMouseListener(new java.awt.event.MouseAdapter() {
                      public void mouseClicked(java.awt.event.MouseEvent evt) {
                          choosablePlotsJlistMouseClicked(evt);
                      }
                  });
                  
                  jScrollPane1.setViewportView(choosablePlotsJlist);
                  
                  jPanel3.add(jScrollPane1);
                
                loginPanel.add(jPanel3);
              
              jTabbedPane1.addTab("Initiate", loginPanel);
            
            projectNameTextArea.setPreferredSize(new java.awt.Dimension(400, 21));
              projectNameTextArea.setMinimumSize(new java.awt.Dimension(400, 21));
              jPanel4.add(projectNameTextArea);
              
              jTabbedPane1.addTab("Project Info", jPanel4);
            
            mainPane.add(jTabbedPane1);
          
          getContentPane().add(mainPane, java.awt.BorderLayout.CENTER);
        
    }//GEN-END:initComponents

    private void choosablePlotsJlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choosablePlotsJlistMouseClicked
        // Add your handling code here:
        System.out.println("DataSourceClientApplet > plot selected ");
        this.targetPlot =  choosablePlotsJlist.getSelectedValue().toString();
        System.out.println("DataSourceClientApplet > the plot: " + choosablePlotsJlist.getSelectedValue().toString() );
        System.out.println("DataSourceClientApplet > updating the varaible fields " );
        
        //update all the plot fields in the other panels
        this.setPlotFields(this.targetPlot);
        
    }//GEN-LAST:event_choosablePlotsJlistMouseClicked

    //method that will set data into all the plot fields
    //
    private void setPlotFields(String plot)
    {
        
        String projectName = source.getProjectName(plot);
        System.out.println("DataSourceClientApplet > projectName: " + projectName );
        
        this.projectNameTextArea.setText(projectName);
    }
    
    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // Add your handling code here:
        System.out.println("DataSourceClientApplet > login" );
        Vector plotList = source.getPlotNames();
        choosablePlotsJlist.setListData(plotList);
        
    }//GEN-LAST:event_loginButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPane;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField loginNameTextArea;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField loginPasswordTextArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList choosablePlotsJlist;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField projectNameTextArea;
    // End of variables declaration//GEN-END:variables

}
