import javax.swing.*;
import java.util.*;
/*
 * PlotDataViewerInterface.java
 *
 * Created on January 27, 2002, 7:54 PM
 */

/**
 *
 * @author  administrator
 */
public class PlotDataViewerInterface extends javax.swing.JFrame {

    /** Creates new form PlotDataViewerInterface */
    public PlotDataViewerInterface() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
                jTabbedPane1 = new javax.swing.JTabbedPane();
                jPanel2 = new javax.swing.JPanel();
                jPanel3 = new javax.swing.JPanel();
                jPanel4 = new javax.swing.JPanel();
                jRadioButton1 = new javax.swing.JRadioButton();
                jPanel5 = new javax.swing.JPanel();
                jRadioButton2 = new javax.swing.JRadioButton();
                jPanel6 = new javax.swing.JPanel();
                jButton1 = new javax.swing.JButton();
                jPanel7 = new javax.swing.JPanel();
                jPanel8 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jTextField1 = new javax.swing.JTextField();
                jList1 = new javax.swing.JList();
                jPanel9 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                jTextField2 = new javax.swing.JTextField();
                jPanel10 = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                jTextField3 = new javax.swing.JTextField();
                jPanel11 = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                jList2 = new javax.swing.JList();
                jPanel12 = new javax.swing.JPanel();
                jPanel13 = new javax.swing.JPanel();
                jLabel4 = new javax.swing.JLabel();
                jPanel14 = new javax.swing.JPanel();
                jLabel5 = new javax.swing.JLabel();
                jTextField4 = new javax.swing.JTextField();
                jLabel6 = new javax.swing.JLabel();
                jTextField5 = new javax.swing.JTextField();
                jLabel7 = new javax.swing.JLabel();
                jComboBox1 = new javax.swing.JComboBox();
                jPanel15 = new javax.swing.JPanel();
                jPanel16 = new javax.swing.JPanel();
                jPanel17 = new javax.swing.JPanel();
                jLabel8 = new javax.swing.JLabel();
                jTextField6 = new javax.swing.JTextField();
                jPanel18 = new javax.swing.JPanel();
                jLabel9 = new javax.swing.JLabel();
                jTextField7 = new javax.swing.JTextField();
                jPanel19 = new javax.swing.JPanel();
                jLabel10 = new javax.swing.JLabel();
                jTextField8 = new javax.swing.JTextField();
                jPanel20 = new javax.swing.JPanel();
                jLabel11 = new javax.swing.JLabel();
                jTextField9 = new javax.swing.JTextField();
                jPanel21 = new javax.swing.JPanel();
                jLabel12 = new javax.swing.JLabel();
                jTextField10 = new javax.swing.JTextField();
                jPanel22 = new javax.swing.JPanel();
                jLabel13 = new javax.swing.JLabel();
                jTextField11 = new javax.swing.JTextField();
                jPanel23 = new javax.swing.JPanel();
                jLabel14 = new javax.swing.JLabel();
                jTextField12 = new javax.swing.JTextField();
                jPanel24 = new javax.swing.JPanel();
                jLabel15 = new javax.swing.JLabel();
                jTextField13 = new javax.swing.JTextField();
                jPanel25 = new javax.swing.JPanel();
                jPanel26 = new javax.swing.JPanel();
                jPanel27 = new javax.swing.JPanel();
                jLabel16 = new javax.swing.JLabel();
                jTextField14 = new javax.swing.JTextField();
                jPanel28 = new javax.swing.JPanel();
                jLabel17 = new javax.swing.JLabel();
                jTextField15 = new javax.swing.JTextField();
                jPanel29 = new javax.swing.JPanel();
                jLabel18 = new javax.swing.JLabel();
                jTextField16 = new javax.swing.JTextField();
                jPanel30 = new javax.swing.JPanel();
                jLabel19 = new javax.swing.JLabel();
                jTextField17 = new javax.swing.JTextField();
                jPanel31 = new javax.swing.JPanel();
                jLabel20 = new javax.swing.JLabel();
                jTextField18 = new javax.swing.JTextField();
                jPanel32 = new javax.swing.JPanel();
                jLabel21 = new javax.swing.JLabel();
                jTextField19 = new javax.swing.JTextField();
                jPanel33 = new javax.swing.JPanel();
                jLabel22 = new javax.swing.JLabel();
                jTextField20 = new javax.swing.JTextField();
                jPanel34 = new javax.swing.JPanel();
                jLabel23 = new javax.swing.JLabel();
                jTextField21 = new javax.swing.JTextField();
                jPanel35 = new javax.swing.JPanel();
                jPanel36 = new javax.swing.JPanel();
                jPanel37 = new javax.swing.JPanel();
                jLabel24 = new javax.swing.JLabel();
                jComboBox2 = new JComboBox(strataMethods);
                jPanel38 = new javax.swing.JPanel();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                jPanel39 = new javax.swing.JPanel();
                jPanel40 = new javax.swing.JPanel();
                jPanel41 = new javax.swing.JPanel();
                jRadioButton3 = new javax.swing.JRadioButton();
                jRadioButton4 = new javax.swing.JRadioButton();
                jPanel42 = new javax.swing.JPanel();
                jLabel25 = new javax.swing.JLabel();
                jTextField22 = new javax.swing.JTextField();
                jPanel43 = new javax.swing.JPanel();
                jScrollPane3 = new javax.swing.JScrollPane();
                jList3 = new javax.swing.JList();
                jPanel44 = new javax.swing.JPanel();
                jPanel45 = new javax.swing.JPanel();
                jLabel26 = new javax.swing.JLabel();
                jComboBox3 = new JComboBox(tncCodes);
                jLabel27 = new javax.swing.JLabel();
                jTextField23 = new javax.swing.JTextField();
                jPanel46 = new javax.swing.JPanel();
                jLabel28 = new javax.swing.JLabel();
                jTextField24 = new javax.swing.JTextField();
                jPanel47 = new javax.swing.JPanel();
                jPanel48 = new javax.swing.JPanel();
                jButton2 = new javax.swing.JButton();
                jButton3 = new javax.swing.JButton();
                
                addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent evt) {
                        exitForm(evt);
                    }
                });
                
                jTabbedPane1.setFont(new java.awt.Font("Default", 0, 12));
                jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));
                
                jPanel2.setForeground(java.awt.Color.blue);
                jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));
                
                jPanel3.setBorder(new javax.swing.border.EtchedBorder());
                jPanel3.setForeground(java.awt.Color.lightGray);
                jPanel3.setPreferredSize(new java.awt.Dimension(199, 100));
                jPanel3.setMinimumSize(new java.awt.Dimension(199, 130));
                jPanel3.setMaximumSize(new java.awt.Dimension(32771, 130));
                jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
                
                jRadioButton1.setForeground(java.awt.Color.blue);
                jRadioButton1.setFont(new java.awt.Font("Default", 0, 12));
                jRadioButton1.setText("Intitialize New Project:");
                jPanel4.add(jRadioButton1);
                
                jPanel3.add(jPanel4);
              
              jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
                
                jRadioButton2.setForeground(java.awt.Color.blue);
                jRadioButton2.setFont(new java.awt.Font("Default", 0, 12));
                jRadioButton2.setText("Work With Last Project:");
                jPanel5.add(jRadioButton2);
                
                jPanel3.add(jPanel5);
              
              jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
                
                jButton1.setText("Choose Project File");
                jPanel6.add(jButton1);
                
                jPanel3.add(jPanel6);
              
              jPanel2.add(jPanel3);
            
            jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.Y_AXIS));
                
                jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
                
                jPanel8.setMaximumSize(new java.awt.Dimension(32767, 27));
                jLabel1.setText("Project Description");
                jLabel1.setForeground(java.awt.Color.blue);
                jLabel1.setFont(new java.awt.Font("Default", 0, 12));
                jPanel8.add(jLabel1);
                
                jTextField1.setBackground(java.awt.Color.pink);
                jTextField1.setPreferredSize(new java.awt.Dimension(200, 17));
                jPanel8.add(jTextField1);
                
                jPanel8.add(jList1);
                
                jPanel7.add(jPanel8);
              
              jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
                
                jPanel9.setMaximumSize(new java.awt.Dimension(32767, 27));
                jLabel2.setText("ProjectName: ");
                jLabel2.setForeground(java.awt.Color.blue);
                jLabel2.setFont(new java.awt.Font("Default", 0, 12));
                jPanel9.add(jLabel2);
                
                jTextField2.setBackground(java.awt.Color.pink);
                jTextField2.setPreferredSize(new java.awt.Dimension(200, 17));
                jPanel9.add(jTextField2);
                
                jPanel7.add(jPanel9);
              
              jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
                
                jPanel10.setPreferredSize(new java.awt.Dimension(288, 40));
                jPanel10.setMinimumSize(new java.awt.Dimension(92, 40));
                jPanel10.setMaximumSize(new java.awt.Dimension(32767, 40));
                jLabel3.setText("Project File:");
                jLabel3.setForeground(java.awt.Color.blue);
                jLabel3.setFont(new java.awt.Font("Default", 0, 12));
                jPanel10.add(jLabel3);
                
                jTextField3.setBackground(java.awt.Color.pink);
                jTextField3.setPreferredSize(new java.awt.Dimension(200, 17));
                jPanel10.add(jTextField3);
                
                jPanel7.add(jPanel10);
              
              jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.X_AXIS));
                  
                  jPanel11.setPreferredSize(new java.awt.Dimension(250, 120));
                  jPanel11.setMaximumSize(new java.awt.Dimension(250, 120));
                  jScrollPane1.setViewportView(jList2);
                  
                  jPanel11.add(jScrollPane1);
                
                jPanel7.add(jPanel11);
              
              jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.Y_AXIS));
                  
                  jPanel12.setMaximumSize(new java.awt.Dimension(32767, 27));
                  jLabel4.setText("Project Author");
                  jLabel4.setForeground(java.awt.Color.blue);
                  jLabel4.setFont(new java.awt.Font("Default", 0, 12));
                  jPanel13.add(jLabel4);
                  
                  jPanel12.add(jPanel13);
                
                jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
                  
                  jLabel5.setText("First Name: ");
                  jPanel14.add(jLabel5);
                  
                  jTextField4.setBackground(java.awt.Color.pink);
                  jTextField4.setPreferredSize(new java.awt.Dimension(100, 17));
                  jPanel14.add(jTextField4);
                  
                  jLabel6.setText("Last Name: ");
                  jPanel14.add(jLabel6);
                  
                  jTextField5.setBackground(java.awt.Color.pink);
                  jTextField5.setPreferredSize(new java.awt.Dimension(100, 17));
                  jPanel14.add(jTextField5);
                  
                  jLabel7.setText("Role: ");
                  jPanel14.add(jLabel7);
                  
                  jComboBox1.setBackground(java.awt.Color.pink);
                  jComboBox1.setPreferredSize(new java.awt.Dimension(40, 22));
                  jComboBox1.setMinimumSize(new java.awt.Dimension(40, 22));
                  jPanel14.add(jComboBox1);
                  
                  jPanel12.add(jPanel14);
                
                jPanel7.add(jPanel12);
              
              jPanel2.add(jPanel7);
            
            jTabbedPane1.addTab("Project", jPanel2);
          
          jPanel15.setLayout(new java.awt.BorderLayout());
                
                jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
                
                jPanel17.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
                
                jLabel8.setText("Plot Code: ");
                jLabel8.setForeground(java.awt.Color.blue);
                jLabel8.setFont(new java.awt.Font("Default", 0, 12));
                jPanel17.add(jLabel8);
                
                jTextField6.setBackground(java.awt.Color.pink);
                jTextField6.setPreferredSize(new java.awt.Dimension(200, 17));
                jPanel17.add(jTextField6);
                
                jPanel16.add(jPanel17);
              
              jPanel18.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
                
                jLabel9.setText("State: ");
                jLabel9.setForeground(java.awt.Color.blue);
                jLabel9.setFont(new java.awt.Font("Default", 0, 12));
                jPanel18.add(jLabel9);
                
                jTextField7.setBackground(java.awt.Color.pink);
                jTextField7.setPreferredSize(new java.awt.Dimension(200, 17));
                jPanel18.add(jTextField7);
                
                jPanel16.add(jPanel18);
              
              jPanel19.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
                
                jLabel10.setText("Country: ");
                jLabel10.setForeground(java.awt.Color.blue);
                jLabel10.setFont(new java.awt.Font("Default", 0, 12));
                jPanel19.add(jLabel10);
                
                jTextField8.setBackground(java.awt.Color.pink);
                jTextField8.setPreferredSize(new java.awt.Dimension(200, 17));
                jPanel19.add(jTextField8);
                
                jPanel16.add(jPanel19);
              
              jPanel20.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
                
                jLabel11.setText("County: ");
                jLabel11.setForeground(java.awt.Color.blue);
                jLabel11.setFont(new java.awt.Font("Default", 0, 12));
                jPanel20.add(jLabel11);
                
                jTextField9.setBackground(java.awt.Color.pink);
                jTextField9.setPreferredSize(new java.awt.Dimension(200, 17));
                jPanel20.add(jTextField9);
                
                jPanel16.add(jPanel20);
              
              jPanel21.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
                
                jLabel12.setText("USGS Quad:");
                jLabel12.setForeground(java.awt.Color.blue);
                jLabel12.setFont(new java.awt.Font("Default", 0, 12));
                jPanel21.add(jLabel12);
                
                jTextField10.setBackground(java.awt.Color.pink);
                jTextField10.setPreferredSize(new java.awt.Dimension(200, 17));
                jPanel21.add(jTextField10);
                
                jPanel16.add(jPanel21);
              
              jPanel22.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
                
                jLabel13.setText("Latitude: ");
                jLabel13.setForeground(java.awt.Color.blue);
                jLabel13.setFont(new java.awt.Font("Default", 0, 12));
                jPanel22.add(jLabel13);
                
                jTextField11.setBackground(java.awt.Color.pink);
                jTextField11.setPreferredSize(new java.awt.Dimension(200, 17));
                jPanel22.add(jTextField11);
                
                jPanel16.add(jPanel22);
              
              jPanel23.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
                
                jLabel14.setText("Longitude: ");
                jLabel14.setForeground(java.awt.Color.blue);
                jLabel14.setFont(new java.awt.Font("Default", 0, 12));
                jPanel23.add(jLabel14);
                
                jTextField12.setBackground(java.awt.Color.pink);
                jTextField12.setPreferredSize(new java.awt.Dimension(200, 17));
                jPanel23.add(jTextField12);
                
                jPanel16.add(jPanel23);
              
              jPanel24.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
                
                jLabel15.setText("Datum: ");
                jLabel15.setForeground(java.awt.Color.blue);
                jLabel15.setFont(new java.awt.Font("Default", 0, 12));
                jPanel24.add(jLabel15);
                
                jTextField13.setBackground(java.awt.Color.pink);
                jTextField13.setPreferredSize(new java.awt.Dimension(200, 17));
                jPanel24.add(jTextField13);
                
                jPanel16.add(jPanel24);
              
              jPanel15.add(jPanel16, java.awt.BorderLayout.CENTER);
            
            jTabbedPane1.addTab("Plot", jPanel15);
          
          jPanel25.setLayout(new java.awt.BorderLayout());
                
                jPanel26.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
                
                jPanel27.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
                
                jLabel16.setText("Start Date:");
                jLabel16.setForeground(java.awt.Color.blue);
                jLabel16.setFont(new java.awt.Font("Default", 0, 12));
                jPanel27.add(jLabel16);
                
                jTextField14.setBackground(java.awt.Color.pink);
                jTextField14.setPreferredSize(new java.awt.Dimension(200, 17));
                jPanel27.add(jTextField14);
                
                jPanel26.add(jPanel27);
              
              jPanel28.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
                
                jLabel17.setText("Stop Date:");
                jLabel17.setForeground(java.awt.Color.blue);
                jLabel17.setFont(new java.awt.Font("Default", 0, 12));
                jPanel28.add(jLabel17);
                
                jTextField15.setBackground(java.awt.Color.pink);
                jTextField15.setPreferredSize(new java.awt.Dimension(200, 17));
                jPanel28.add(jTextField15);
                
                jPanel26.add(jPanel28);
              
              jPanel29.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
                
                jLabel18.setText("Soil Type:");
                jLabel18.setForeground(java.awt.Color.blue);
                jLabel18.setFont(new java.awt.Font("Default", 0, 12));
                jPanel29.add(jLabel18);
                
                jTextField16.setBackground(java.awt.Color.pink);
                jTextField16.setPreferredSize(new java.awt.Dimension(200, 17));
                jPanel29.add(jTextField16);
                
                jPanel26.add(jPanel29);
              
              jPanel30.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
                
                jLabel19.setText("Soil Depth: ");
                jLabel19.setForeground(java.awt.Color.blue);
                jLabel19.setFont(new java.awt.Font("Default", 0, 12));
                jPanel30.add(jLabel19);
                
                jTextField17.setBackground(java.awt.Color.pink);
                jTextField17.setPreferredSize(new java.awt.Dimension(200, 17));
                jPanel30.add(jTextField17);
                
                jPanel26.add(jPanel30);
              
              jPanel31.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
                
                jLabel20.setText("Soil Depth Range");
                jLabel20.setForeground(java.awt.Color.blue);
                jLabel20.setFont(new java.awt.Font("Default", 0, 12));
                jPanel31.add(jLabel20);
                
                jTextField18.setBackground(java.awt.Color.pink);
                jTextField18.setPreferredSize(new java.awt.Dimension(200, 17));
                jPanel31.add(jTextField18);
                
                jPanel26.add(jPanel31);
              
              jPanel32.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
                
                jLabel21.setText("Percent Rock: ");
                jLabel21.setForeground(java.awt.Color.blue);
                jLabel21.setFont(new java.awt.Font("Default", 0, 12));
                jPanel32.add(jLabel21);
                
                jTextField19.setBackground(java.awt.Color.pink);
                jTextField19.setPreferredSize(new java.awt.Dimension(200, 17));
                jPanel32.add(jTextField19);
                
                jPanel26.add(jPanel32);
              
              jPanel33.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
                
                jLabel22.setText("Percent Organic Material");
                jLabel22.setForeground(java.awt.Color.blue);
                jLabel22.setFont(new java.awt.Font("Default", 0, 12));
                jPanel33.add(jLabel22);
                
                jTextField20.setBackground(java.awt.Color.pink);
                jTextField20.setPreferredSize(new java.awt.Dimension(200, 17));
                jPanel33.add(jTextField20);
                
                jPanel26.add(jPanel33);
              
              jPanel34.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
                
                jLabel23.setText("Percent Water: ");
                jLabel23.setForeground(java.awt.Color.blue);
                jLabel23.setFont(new java.awt.Font("Default", 0, 12));
                jPanel34.add(jLabel23);
                
                jTextField21.setBackground(java.awt.Color.pink);
                jTextField21.setPreferredSize(new java.awt.Dimension(200, 17));
                jPanel34.add(jTextField21);
                
                jPanel26.add(jPanel34);
              
              jPanel25.add(jPanel26, java.awt.BorderLayout.CENTER);
            
            jTabbedPane1.addTab("Observations", jPanel25);
          
          jPanel35.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
                
                jPanel36.setLayout(new javax.swing.BoxLayout(jPanel36, javax.swing.BoxLayout.Y_AXIS));
                
                jLabel24.setText("Enter a Strata method or pick from the list:");
                jLabel24.setForeground(java.awt.Color.blue);
                jLabel24.setFont(new java.awt.Font("Default", 0, 12));
                jPanel37.add(jLabel24);
                
                jComboBox2.setForeground(java.awt.Color.blue);
                jComboBox2.setBackground(java.awt.Color.pink);
                jComboBox2.setEditable(true);
                jComboBox2.setFont(new java.awt.Font("Default", 0, 12));
                jPanel37.add(jComboBox2);
                
                jPanel36.add(jPanel37);
              
              jTable1.setModel(new javax.swing.table.DefaultTableModel(
                  new Object [][] {
                      {"t1", "Emergent", "", ""},
                      {"t2", "Canopy", null, null},
                      {"t3", "Sub-Canopy", null, null},
                      {"s1", "Tall-Shrub", null, null},
                      {"s2", "Short-Shrub", null, null},
                      {"s3", "Drawrf-Shrub", null, null},
                      {"H", "Herbaceous", null, null},
                      {"N", "Non-Vascular", null, null},
                      {"V", "Vine/Liana", null, null},
                      {"E", "Epiphyte", null, null},
                      {null, null, null, null}
                  },
                  new String [] {
                      "code", "name", "height", "cover"
                  }
                  ) {
                      Class[] types = new Class [] {
                          java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
                      };
                      boolean[] canEdit = new boolean [] {
                          false, false, true, true
                      };
                      
                      public Class getColumnClass(int columnIndex) {
                          return types [columnIndex];
                      }
                      
                      public boolean isCellEditable(int rowIndex, int columnIndex) {
                          return canEdit [columnIndex];
                      }
                  });
                  jScrollPane2.setViewportView(jTable1);
                  
                  jPanel38.add(jScrollPane2);
                
                jPanel36.add(jPanel38);
              
              jPanel35.add(jPanel36);
            
            jTabbedPane1.addTab("Strata", jPanel35);
          
          jPanel39.setLayout(new javax.swing.BoxLayout(jPanel39, javax.swing.BoxLayout.Y_AXIS));
                
                jPanel40.setLayout(new javax.swing.BoxLayout(jPanel40, javax.swing.BoxLayout.Y_AXIS));
                
                jPanel40.setPreferredSize(new java.awt.Dimension(492, 155));
                jPanel40.setMinimumSize(new java.awt.Dimension(312, 75));
                jPanel40.setMaximumSize(new java.awt.Dimension(40000, 150));
                jPanel41.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
                
                jPanel41.setPreferredSize(new java.awt.Dimension(67, 25));
                jPanel41.setMaximumSize(new java.awt.Dimension(32767, 35));
                jRadioButton3.setText("USDA");
                jPanel41.add(jRadioButton3);
                
                jRadioButton4.setLabel("ITIS");
                jPanel41.add(jRadioButton4);
                
                jPanel40.add(jPanel41);
              
              jPanel42.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
                
                jLabel25.setText("Plant Name:");
                jLabel25.setForeground(java.awt.Color.blue);
                jLabel25.setFont(new java.awt.Font("Default", 0, 12));
                jPanel42.add(jLabel25);
                
                jTextField22.setBackground(java.awt.Color.pink);
                jTextField22.setPreferredSize(new java.awt.Dimension(300, 17));
                jTextField22.setMinimumSize(new java.awt.Dimension(120, 17));
                jPanel42.add(jTextField22);
                
                jPanel40.add(jPanel42);
              
              jPanel43.setPreferredSize(new java.awt.Dimension(269, 90));
                  jPanel43.setMinimumSize(new java.awt.Dimension(32, 92));
                  jPanel43.setMaximumSize(new java.awt.Dimension(32767, 90));
                  jScrollPane3.setPreferredSize(new java.awt.Dimension(259, 60));
                  jList3.setVisibleRowCount(3);
                  jScrollPane3.setViewportView(jList3);
                  
                  jPanel43.add(jScrollPane3);
                
                jPanel40.add(jPanel43);
              
              jPanel39.add(jPanel40);
            
            jPanel44.setLayout(new javax.swing.BoxLayout(jPanel44, javax.swing.BoxLayout.Y_AXIS));
                
                jPanel44.setMaximumSize(new java.awt.Dimension(32767, 120));
                jPanel45.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
                
                jLabel26.setText("Strata Code: ");
                jLabel26.setForeground(java.awt.Color.blue);
                jLabel26.setFont(new java.awt.Font("Default", 0, 12));
                jPanel45.add(jLabel26);
                
                jComboBox3.setBackground(java.awt.Color.pink);
                jPanel45.add(jComboBox3);
                
                jLabel27.setText("   Cover Value:   ");
                jLabel27.setForeground(java.awt.Color.blue);
                jLabel27.setFont(new java.awt.Font("Default", 0, 12));
                jPanel45.add(jLabel27);
                
                jTextField23.setBackground(java.awt.Color.pink);
                jTextField23.setPreferredSize(new java.awt.Dimension(40, 17));
                jTextField23.setMinimumSize(new java.awt.Dimension(40, 17));
                jPanel45.add(jTextField23);
                
                jPanel44.add(jPanel45);
              
              jPanel46.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
                
                jLabel28.setText("Cumulative Strata Cover: ");
                jLabel28.setForeground(java.awt.Color.blue);
                jLabel28.setFont(new java.awt.Font("Default", 0, 12));
                jPanel46.add(jLabel28);
                
                jTextField24.setBackground(java.awt.Color.pink);
                jTextField24.setPreferredSize(new java.awt.Dimension(40, 17));
                jTextField24.setMinimumSize(new java.awt.Dimension(40, 17));
                jPanel46.add(jTextField24);
                
                jPanel46.add(jPanel47);
                
                jPanel44.add(jPanel46);
              
              jPanel39.add(jPanel44);
            
            jPanel48.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 12));
              
              jButton2.setForeground(java.awt.Color.blue);
              jButton2.setFont(new java.awt.Font("Default", 0, 12));
              jButton2.setText("New Record");
              jPanel48.add(jButton2);
              
              jButton3.setForeground(java.awt.Color.blue);
              jButton3.setFont(new java.awt.Font("Default", 0, 12));
              jButton3.setText("Save Current Record");
              jPanel48.add(jButton3);
              
              jPanel39.add(jPanel48);
            
            jTabbedPane1.addTab("Plant Cover", jPanel39);
          
          getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);
        
        pack();
    }//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        new PlotDataViewerInterface().show();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList jList3;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables

}
