CREATE TABLE namedPlaceCorrelation
(
NAMEDPLACECORRELATION_ID serial NOT NULL ,
PARENTPLACE_ID Integer NOT NULL ,
CHILDPLACE_ID Integer NOT NULL ,
placeConvergence varchar (20) NOT NULL ,

PRIMARY KEY ( NAMEDPLACECORRELATION_ID )
);

ALTER TABLE namedPlaceCorrelation   ADD CONSTRAINT R1namedPlaceCorrelation_PARENTPLACE_ID FOREIGN KEY (PARENTPLACE_ID)    REFERENCES namedPlace (NAMEDPLACE_ID );

ALTER TABLE namedPlaceCorrelation   ADD CONSTRAINT R2namedPlaceCorrelation_CHILDPLACE_ID FOREIGN KEY (CHILDPLACE_ID)    REFERENCES namedPlace (NAMEDPLACE_ID );
