UPDATE namedPlace SET placeDescription='Alabama' WHERE placeSystem='county' AND length(placecode)=4 AND substr(placeCode,1,1)='1';
UPDATE namedPlace SET placeDescription='Alaska' WHERE placeSystem='county' AND length(placecode)=4 AND substr(placeCode,1,1)='2';
UPDATE namedPlace SET placeDescription='Arizona' WHERE placeSystem='county' AND length(placecode)=4 AND substr(placeCode,1,1)='4';
UPDATE namedPlace SET placeDescription='Arkansas' WHERE placeSystem='county' AND length(placecode)=4 AND substr(placeCode,1,1)='5';
UPDATE namedPlace SET placeDescription='California' WHERE placeSystem='county' AND length(placecode)=4 AND substr(placeCode,1,1)='6';
UPDATE namedPlace SET placeDescription='Colorado' WHERE placeSystem='county' AND length(placecode)=4 AND substr(placeCode,1,1)='8';
UPDATE namedPlace SET placeDescription='Connecticut' WHERE placeSystem='county' AND length(placecode)=4 AND substr(placeCode,1,1)='9';
UPDATE namedPlace SET placeDescription='Delaware' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='10';
UPDATE namedPlace SET placeDescription='District of Columbia' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='11';
UPDATE namedPlace SET placeDescription='Florida' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='12';
UPDATE namedPlace SET placeDescription='Georgia' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='13';
UPDATE namedPlace SET placeDescription='Hawaii' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='15';
UPDATE namedPlace SET placeDescription='Idaho' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='16';
UPDATE namedPlace SET placeDescription='Illinois' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='17';
UPDATE namedPlace SET placeDescription='Indiana' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='18';
UPDATE namedPlace SET placeDescription='Iowa' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='19';
UPDATE namedPlace SET placeDescription='Kansas' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='20';
UPDATE namedPlace SET placeDescription='Kentucky' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='21';
UPDATE namedPlace SET placeDescription='Louisiana' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='22';
UPDATE namedPlace SET placeDescription='Maine' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='23';
UPDATE namedPlace SET placeDescription='Maryland' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='24';
UPDATE namedPlace SET placeDescription='Massachusetts' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='25';
UPDATE namedPlace SET placeDescription='Michigan' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='26';
UPDATE namedPlace SET placeDescription='Minnesota' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='27';
UPDATE namedPlace SET placeDescription='Mississippi' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='28';
UPDATE namedPlace SET placeDescription='Missouri' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='29';
UPDATE namedPlace SET placeDescription='Montana' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='30';
UPDATE namedPlace SET placeDescription='Nebraska' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='31';
UPDATE namedPlace SET placeDescription='Nevada' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='32';
UPDATE namedPlace SET placeDescription='New Hampshire' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='33';
UPDATE namedPlace SET placeDescription='New Jersey' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='34';
UPDATE namedPlace SET placeDescription='New Mexico' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='35';
UPDATE namedPlace SET placeDescription='New York' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='36';
UPDATE namedPlace SET placeDescription='North Carolina' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='37';
UPDATE namedPlace SET placeDescription='North Dakota' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='38';
UPDATE namedPlace SET placeDescription='Ohio' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='39';
UPDATE namedPlace SET placeDescription='Oklahoma' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='40';
UPDATE namedPlace SET placeDescription='Oregon' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='41';
UPDATE namedPlace SET placeDescription='Pennsylvania' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='42';
UPDATE namedPlace SET placeDescription='Rhode Island' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='44';
UPDATE namedPlace SET placeDescription='South Carolina' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='45';
UPDATE namedPlace SET placeDescription='South Dakota' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='46';
UPDATE namedPlace SET placeDescription='Tennessee' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='47';
UPDATE namedPlace SET placeDescription='Texas' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='48';
UPDATE namedPlace SET placeDescription='Utah' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='49';
UPDATE namedPlace SET placeDescription='Vermont' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='50';
UPDATE namedPlace SET placeDescription='Virginia' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='51';
UPDATE namedPlace SET placeDescription='Washington' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='53';
UPDATE namedPlace SET placeDescription='West Virginia' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='54';
UPDATE namedPlace SET placeDescription='Wisconsin' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='55';
UPDATE namedPlace SET placeDescription='Wyoming' WHERE placeSystem='county' AND length(placecode)=5 AND substr(placeCode,1,2)='56';